     ****************************************************************
     ***  pascal2.s
     ***  Generated by Small-C Compiler on 8-Mar-2015 6:32:00 PM
     ****************************************************************
     ****************************************************************

     READ      EQU  001                * Read area
     PUNCH     EQU  101                * Punch area
     PRINT     EQU  201                * Print area
     
     PRCPOS    DCW  000                * char position in print area
     PUCPOS    DCW  000                * char position in punch area
     PUNSIZ    DCW  @080@              * Size of punch area
     PRTSIZ    DCW  @132@              * Size of print area
     EOS       DCW  @'@                * End Of String char
     EOL       DCW  @;@                * End Of Line char

               ORG  87
     X1        DSA  0                  * INDEX REGISTER 1
               ORG  92
     X2        DSA  0                  * INDEX REGISTER 2
               ORG  97
     X3        DSA  0                  * INDEX REGISTER 3
     
     * I need a single digit flag - should I replace this with a DA?
     RF        EQU  340
     
     ****************************************************************  
     * SET THE START POSITION OF CODE
               ORG  5500
     START     NOP  

     * SET THE STACK POINTER
               SBR  X2,400

               MCW  X2,X3
               LCA  LCEAAA,5005
               LCA  LDEAAA,5025
               LCA  LEEAAA,5028
               LCA  LFEAAA,5033
               LCA  EOS,5022
               LCA  @F@,5021
               LCA  @E@,5020
               LCA  @D@,5019
               LCA  @C@,5018
               LCA  @B@,5017
               LCA  @A@,5016
               LCA  @9@,5015
               LCA  @8@,5014
               LCA  @7@,5013
               LCA  @6@,5012
               LCA  @5@,5011
               LCA  @4@,5010
               LCA  @3@,5009
               LCA  @2@,5008
               LCA  @1@,5007
               LCA  @0@,5006
               LCA  EOS,5040
               LCA  @C@,5039
               LCA  @%@,5038
               LCA  @D@,5037
               LCA  @%@,5036
               LCA  EOS,5077
               LCA  EOL,5076
               LCA  EOL,5075
               LCA  @S@,5074
               LCA  @N@,5073
               LCA  @O@,5072
               LCA  @I@,5071
               LCA  @T@,5070
               LCA  @A@,5069
               LCA  @R@,5068
               LCA  @E@,5067
               LCA  @T@,5066
               LCA  @I@,5065
               LCA  @ @,5064
               LCA  @D@,5063
               LCA  @%@,5062
               LCA  @ @,5061
               LCA  @H@,5060
               LCA  @T@,5059
               LCA  @I@,5058
               LCA  @W@,5057
               LCA  @ @,5056
               LCA  @E@,5055
               LCA  @L@,5054
               LCA  @G@,5053
               LCA  @N@,5052
               LCA  @A@,5051
               LCA  @I@,5050
               LCA  @R@,5049
               LCA  @T@,5048
               LCA  @ @,5047
               LCA  @L@,5046
               LCA  @A@,5045
               LCA  @C@,5044
               LCA  @S@,5043
               LCA  @A@,5042
               LCA  @P@,5041
               LCA  EOS,5085
               LCA  EOL,5084
               LCA  @.@,5083
               LCA  @E@,5082
               LCA  @N@,5081
               LCA  @O@,5080
               LCA  @D@,5079
               LCA  EOL,5078
               B    LTDAAA
               H    

     * **********************************************************************
     * FunctionDefinition(strlen)
     * **********************************************************************
     LFAAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3

     * ***********************
     * BeginBlock (LGAAAA:null)
               LCA  LKFAAA,8+X3
               MA   LLFAAA,X2
     * WhileStatement (((str[(++len)]) != '\0')) retree.statement.EmptyStatement@19b5080a top:LHAAAA bottom:LIAAAA)
     LHAAAA    NOP  
     * NotEqualExpression ((str[(++len)]) != '\0')
     * SubScriptEpression (str[(++len)])
     * VariableExpression (str : 15997+X3)
     * Push (15997+X3:3)
               MA   LOFAAA,X2
               LCA  15997+X3,0+X2
     * PreIncrement((++len)
     * Push (LLFAAA:3)
               MA   LOFAAA,X2
               LCA  LLFAAA,0+X2
               MA   X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
               A    LQFAAA,0+X1
     * Push (0+X1:5)
               MA   LRFAAA,X2
               LCA  0+X1,0+X2
     * raw index on the stack
     * Push (LQFAAA:5)
               MA   LRFAAA,X2
               LCA  LQFAAA,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
     * STACK TOP IS NOW ARRAY INDEX
               B    LTFAAA
               MA   0+X2,15997+X2
     * Pop (3)
               MA   LPFAAA,X2
     * STACK top is location in array now.
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Push (0+X1:1)
               MA   LAGAAA,X2
               LCA  0+X1,0+X2
     * ConstantExpression ('\0' : EOS)
     * Push (EOS:1)
               MA   LAGAAA,X2
               LCA  EOS,0+X2
               C    0+X2,15999+X2
     * Pop (1)
               MA   LBGAAA,X2
     * Pop (1)
               MA   LBGAAA,X2
     * Push (LQFAAA:5)
               MA   LRFAAA,X2
               LCA  LQFAAA,0+X2
               BE   LMFAAA
               B    LNFAAA
     LMFAAA    MCW  LCGAAA,0+X2
     LNFAAA    NOP  
               MCS  0+X2,0+X2
     * Pop (5)
               MA   LSFAAA,X2
               BCE  LIAAAA,5+X2, 
               B    LHAAAA
     LIAAAA    NOP  
     * VariableExpression (len : 8+X3)
     * Push (8+X3:5)
               MA   LRFAAA,X2
               LCA  8+X3,0+X2
     * Pop (15994+X3:5)
               LCA  0+X2,15994+X3
               MA   LSFAAA,X2
     * set the return flag, so we know do deallocate our stack
               MCW  @R@,RF
     * and branch
               B    LGAAAA
     LGAAAA    NOP  
               MA   LDGAAA,X2
               MCW  @ @,RF
     * EndBlock (LGAAAA:null)
     * ***********************

               LCA  3+X3,X1
               B    0+X1

     * **********************************************************************
     * FunctionDefinition(pascals)
     * **********************************************************************
     LNDAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3

     * ***********************
     * BeginBlock (LODAAA:null)
               MA   LEGAAA,X2
     * ForStatement ((i = 1); (i < d); (i++)) (LPDAAA:LODAAA) top:LQDAAA bottom:LRDAAA continue:LSDAAA)
     * Assignment (i = 1)
     * ConstantExpression (1 : LQFAAA)
     * Push (LQFAAA:5)
               MA   LRFAAA,X2
               LCA  LQFAAA,0+X2
     * Push (LLFAAA:3)
               MA   LOFAAA,X2
               LCA  LLFAAA,0+X2
               MA   X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:5)
               LCA  0+X2,0+X1
               MA   LSFAAA,X2
     LQDAAA    NOP  
     * LessThanExpression (i < d)
     * VariableExpression (i : 8+X3)
     * Push (8+X3:5)
               MA   LRFAAA,X2
               LCA  8+X3,0+X2
               B    LFGAAA
     * VariableExpression (d : 15991+X3)
     * Push (15991+X3:5)
               MA   LRFAAA,X2
               LCA  15991+X3,0+X2
               B    LFGAAA
               C    0+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
               MCW  LCGAAA,0+X2
               BL   LHGAAA
               B    LIGAAA
     LHGAAA    MCW  LQFAAA,0+X2
     LIGAAA    NOP  
               MCS  0+X2,0+X2
     * Pop (5)
               MA   LSFAAA,X2
               BCE  LRDAAA,5+X2, 

     * ***********************
     * BeginBlock (LPDAAA:LODAAA)
     * FunctionCallExpr printf("%d%c", ((y[i]) = ((x[(i - 1)]) + (x[i]))), ((i < (d - 1)) ? ' ' : '\n'))
     * Push (5)
               MA   LRFAAA,X2
     * TernaryExpression ((i < (d - 1)) ? ' ' : '\n')
     * LessThanExpression (i < (d - 1))
     * VariableExpression (i : 8+X3)
     * Push (8+X3:5)
               MA   LRFAAA,X2
               LCA  8+X3,0+X2
               B    LFGAAA
     * Subtraction (d - 1)
     * VariableExpression (d : 15991+X3)
     * Push (15991+X3:5)
               MA   LRFAAA,X2
               LCA  15991+X3,0+X2
     * ConstantExpression (1 : LQFAAA)
     * Push (LQFAAA:5)
               MA   LRFAAA,X2
               LCA  LQFAAA,0+X2
               S    0+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
               B    LFGAAA
               C    0+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
               MCW  LCGAAA,0+X2
               BL   LLGAAA
               B    LMGAAA
     LLGAAA    MCW  LQFAAA,0+X2
     LMGAAA    NOP  
               MCS  0+X2,0+X2
     * Pop (5)
               MA   LSFAAA,X2
               BCE  LJGAAA,5+X2, 
     * ConstantExpression (' ' : @ @)
     * Push (@ @:1)
               MA   LAGAAA,X2
               LCA  @ @,0+X2
               B    LKGAAA
     LJGAAA    NOP  
     * ConstantExpression ('\n' : EOL)
     * Push (EOL:1)
               MA   LAGAAA,X2
               LCA  EOL,0+X2
     LKGAAA    NOP  
     * Assignment ((y[i]) = ((x[(i - 1)]) + (x[i])))
     * Addition ((x[(i - 1)]) + (x[i]))
     * SubScriptEpression (x[(i - 1)])
     * VariableExpression (x : 15997+X3)
     * Push (15997+X3:3)
               MA   LOFAAA,X2
               LCA  15997+X3,0+X2
     * Subtraction (i - 1)
     * VariableExpression (i : 8+X3)
     * Push (8+X3:5)
               MA   LRFAAA,X2
               LCA  8+X3,0+X2
     * ConstantExpression (1 : LQFAAA)
     * Push (LQFAAA:5)
               MA   LRFAAA,X2
               LCA  LQFAAA,0+X2
               S    0+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
     * raw index on the stack
     * Push (LNGAAA:5)
               MA   LRFAAA,X2
               LCA  LNGAAA,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
     * STACK TOP IS NOW ARRAY INDEX
               B    LTFAAA
               MA   0+X2,15997+X2
     * Pop (3)
               MA   LPFAAA,X2
     * STACK top is location in array now.
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Push (0+X1:5)
               MA   LRFAAA,X2
               LCA  0+X1,0+X2
     * SubScriptEpression (x[i])
     * VariableExpression (x : 15997+X3)
     * Push (15997+X3:3)
               MA   LOFAAA,X2
               LCA  15997+X3,0+X2
     * VariableExpression (i : 8+X3)
     * Push (8+X3:5)
               MA   LRFAAA,X2
               LCA  8+X3,0+X2
     * raw index on the stack
     * Push (LNGAAA:5)
               MA   LRFAAA,X2
               LCA  LNGAAA,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
     * STACK TOP IS NOW ARRAY INDEX
               B    LTFAAA
               MA   0+X2,15997+X2
     * Pop (3)
               MA   LPFAAA,X2
     * STACK top is location in array now.
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Push (0+X1:5)
               MA   LRFAAA,X2
               LCA  0+X1,0+X2
               A    0+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
     * VariableExpression (y : 15994+X3)
     * Push (15994+X3:3)
               MA   LOFAAA,X2
               LCA  15994+X3,0+X2
     * VariableExpression (i : 8+X3)
     * Push (8+X3:5)
               MA   LRFAAA,X2
               LCA  8+X3,0+X2
     * raw index on the stack
     * Push (LNGAAA:5)
               MA   LRFAAA,X2
               LCA  LNGAAA,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
     * STACK TOP IS NOW ARRAY INDEX
               B    LTFAAA
               MA   0+X2,15997+X2
     * Pop (3)
               MA   LPFAAA,X2
     * STACK top is location in array now.
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
               LCA  0+X2,0+X1
     * ArrayNameExpresssion("%d%c":char [5])
     * Push (LOGAAA:3)
               MA   LOFAAA,X2
               LCA  LOGAAA,0+X2
     * Push (X3:3)
               MA   LOFAAA,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LNCAAA
     * Pop (X3:3)
               LCA  0+X2,X3
               MA   LPFAAA,X2
     * Pop (3)
               MA   LPFAAA,X2
     * Pop (5)
               MA   LSFAAA,X2
     * Pop (1)
               MA   LBGAAA,X2
     * Pop (5)
               MA   LSFAAA,X2
     LPDAAA    NOP  
               BCE  LODAAA,RF,R
     * EndBlock (LPDAAA:LODAAA)
     * ***********************

     LSDAAA    NOP  
     * PostIncrement (i++)
     * Push (LLFAAA:3)
               MA   LOFAAA,X2
               LCA  LLFAAA,0+X2
               MA   X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
               A    LQFAAA,0+X1
               B    LQDAAA
     LRDAAA    NOP  
     * TernaryExpression ((20 >= d) ? pascals(y, x, (d + 1)) : 0)
     * GreaterThanOrEqualExpression((20 >= d)
     * ConstantExpression (20 : LRGAAA)
     * Push (LRGAAA:5)
               MA   LRFAAA,X2
               LCA  LRGAAA,0+X2
               B    LFGAAA
     * VariableExpression (d : 15991+X3)
     * Push (15991+X3:5)
               MA   LRFAAA,X2
               LCA  15991+X3,0+X2
               B    LFGAAA
               C    0+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
               MCW  LQFAAA,0+X2
               BL   LSGAAA
               B    LTGAAA
     LSGAAA    MCW  LCGAAA,0+X2
     LTGAAA    NOP  
               MCS  0+X2,0+X2
     * Pop (5)
               MA   LSFAAA,X2
               BCE  LPGAAA,5+X2, 
     * FunctionCallExpr pascals(y, x, (d + 1))
     * Push (5)
               MA   LRFAAA,X2
     * Addition (d + 1)
     * VariableExpression (d : 15991+X3)
     * Push (15991+X3:5)
               MA   LRFAAA,X2
               LCA  15991+X3,0+X2
     * ConstantExpression (1 : LQFAAA)
     * Push (LQFAAA:5)
               MA   LRFAAA,X2
               LCA  LQFAAA,0+X2
               A    0+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
     * VariableExpression (x : 15997+X3)
     * Push (15997+X3:3)
               MA   LOFAAA,X2
               LCA  15997+X3,0+X2
     * VariableExpression (y : 15994+X3)
     * Push (15994+X3:3)
               MA   LOFAAA,X2
               LCA  15994+X3,0+X2
     * Push (X3:3)
               MA   LOFAAA,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LNDAAA
     * Pop (X3:3)
               LCA  0+X2,X3
               MA   LPFAAA,X2
     * Pop (3)
               MA   LPFAAA,X2
     * Pop (3)
               MA   LPFAAA,X2
     * Pop (5)
               MA   LSFAAA,X2
               B    LQGAAA
     LPGAAA    NOP  
     * ConstantExpression (0 : LCGAAA)
     * Push (LCGAAA:5)
               MA   LRFAAA,X2
               LCA  LCGAAA,0+X2
     LQGAAA    NOP  
     * Pop (15986+X3:5)
               LCA  0+X2,15986+X3
               MA   LSFAAA,X2
     * set the return flag, so we know do deallocate our stack
               MCW  @R@,RF
     * and branch
               B    LODAAA
     LODAAA    NOP  
               MA   LUGAAA,X2
               MCW  @ @,RF
     * EndBlock (LODAAA:null)
     * ***********************

               LCA  3+X3,X1
               B    0+X1

     * **********************************************************************
     * FunctionDefinition(printf)
     * **********************************************************************
     LNCAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3

     * ***********************
     * BeginBlock (LOCAAA:null)
               MA   LVGAAA,X2
     * Assignment (arg = ((*char) (( &cformat_str ) + 15997)))
     * Addition (( &cformat_str ) + 15997)
     * AddressOfExpression ( &cformat_str )
     * Push (LPFAAA:3)
               MA   LOFAAA,X2
               LCA  LPFAAA,0+X2
               MA   X3,0+X2
     * ConstantExpression (15997 : LPFAAA)
     * Push (LPFAAA:3)
               MA   LOFAAA,X2
               LCA  LPFAAA,0+X2
               MA   0+X2,15997+X2
     * Pop (3)
               MA   LPFAAA,X2
     * Push (LWGAAA:3)
               MA   LOFAAA,X2
               LCA  LWGAAA,0+X2
               MA   X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:3)
               LCA  0+X2,0+X1
               MA   LPFAAA,X2
     * WhileStatement (((c = ( *(cformat_str++) )) != '\0')) (LPCAAA:LOCAAA) top:LHDAAA bottom:LIDAAA)
     LHDAAA    NOP  
     * NotEqualExpression ((c = ( *(cformat_str++) )) != '\0')
     * Assignment (c = ( *(cformat_str++) ))
     * DereferenceExpression ( *(cformat_str++) )
     * PostIncrement (cformat_str++)
     * Push (LPFAAA:3)
               MA   LOFAAA,X2
               LCA  LPFAAA,0+X2
               MA   X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Push (0+X1:3)
               MA   LOFAAA,X2
               LCA  0+X1,0+X2
               MA   LAGAAA,0+X1
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Push (0+X1:1)
               MA   LAGAAA,X2
               LCA  0+X1,0+X2
     * Push (LVGAAA:3)
               MA   LOFAAA,X2
               LCA  LVGAAA,0+X2
               MA   X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
               LCA  0+X2,0+X1
     * ConstantExpression ('\0' : EOS)
     * Push (EOS:1)
               MA   LAGAAA,X2
               LCA  EOS,0+X2
               C    0+X2,15999+X2
     * Pop (1)
               MA   LBGAAA,X2
     * Pop (1)
               MA   LBGAAA,X2
     * Push (LQFAAA:5)
               MA   LRFAAA,X2
               LCA  LQFAAA,0+X2
               BE   LXGAAA
               B    LYGAAA
     LXGAAA    MCW  LCGAAA,0+X2
     LYGAAA    NOP  
               MCS  0+X2,0+X2
     * Pop (5)
               MA   LSFAAA,X2
               BCE  LIDAAA,5+X2, 

     * ***********************
     * BeginBlock (LPCAAA:LOCAAA)
     * IfStatement if((c != '%') then (LQCAAA:LPCAAA) else (LRCAAA:LPCAAA))
     * NotEqualExpression (c != '%')
     * VariableExpression (c : 7+X3)
     * Push (7+X3:1)
               MA   LAGAAA,X2
               LCA  7+X3,0+X2
     * ConstantExpression ('%' : @%@)
     * Push (@%@:1)
               MA   LAGAAA,X2
               LCA  @%@,0+X2
               C    0+X2,15999+X2
     * Pop (1)
               MA   LBGAAA,X2
     * Pop (1)
               MA   LBGAAA,X2
     * Push (LQFAAA:5)
               MA   LRFAAA,X2
               LCA  LQFAAA,0+X2
               BE   LZGAAA
               B    LAHAAA
     LZGAAA    MCW  LCGAAA,0+X2
     LAHAAA    NOP  
               MCS  0+X2,0+X2
     * Pop (5)
               MA   LSFAAA,X2
               BCE  LFDAAA,5+X2, 

     * ***********************
     * BeginBlock (LQCAAA:LPCAAA)
     * FunctionCallExpr putchar(c)
     * Push (5)
               MA   LRFAAA,X2
     * VariableExpression (c : 7+X3)
     * Push (7+X3:1)
               MA   LAGAAA,X2
               LCA  7+X3,0+X2
     * Push (X3:3)
               MA   LOFAAA,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LJBAAA
     * Pop (X3:3)
               LCA  0+X2,X3
               MA   LPFAAA,X2
     * Pop (1)
               MA   LBGAAA,X2
     * Pop (5)
               MA   LSFAAA,X2
     LQCAAA    NOP  
               BCE  LPCAAA,RF,R
     * EndBlock (LQCAAA:LPCAAA)
     * ***********************

               B    LGDAAA
     LFDAAA    NOP  

     * ***********************
     * BeginBlock (LRCAAA:LPCAAA)
     * Assignment (c = ( *(cformat_str++) ))
     * DereferenceExpression ( *(cformat_str++) )
     * PostIncrement (cformat_str++)
     * Push (LPFAAA:3)
               MA   LOFAAA,X2
               LCA  LPFAAA,0+X2
               MA   X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Push (0+X1:3)
               MA   LOFAAA,X2
               LCA  0+X1,0+X2
               MA   LAGAAA,0+X1
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Push (0+X1:1)
               MA   LAGAAA,X2
               LCA  0+X1,0+X2
     * Push (LVGAAA:3)
               MA   LOFAAA,X2
               LCA  LVGAAA,0+X2
               MA   X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:1)
               LCA  0+X2,0+X1
               MA   LBGAAA,X2
     * IfStatement if((c == '%') then (LSCAAA:LRCAAA) else if((c == 'C') then (LTCAAA:LRCAAA) else if((c == 'S') then (LUCAAA:LRCAAA) else if((c == 'D') then (LVCAAA:LRCAAA) else (LWCAAA:LRCAAA)))))
     * EqualExpression (c == '%')
     * VariableExpression (c : 7+X3)
     * Push (7+X3:1)
               MA   LAGAAA,X2
               LCA  7+X3,0+X2
     * ConstantExpression ('%' : @%@)
     * Push (@%@:1)
               MA   LAGAAA,X2
               LCA  @%@,0+X2
               C    0+X2,15999+X2
     * Pop (1)
               MA   LBGAAA,X2
     * Pop (1)
               MA   LBGAAA,X2
     * Push (LCGAAA:5)
               MA   LRFAAA,X2
               LCA  LCGAAA,0+X2
               BE   LBHAAA
               B    LCHAAA
     LBHAAA    MCW  LQFAAA,0+X2
     LCHAAA    NOP  
               MCS  0+X2,0+X2
     * Pop (5)
               MA   LSFAAA,X2
               BCE  LDDAAA,5+X2, 

     * ***********************
     * BeginBlock (LSCAAA:LRCAAA)
     * FunctionCallExpr putchar('%')
     * Push (5)
               MA   LRFAAA,X2
     * ConstantExpression ('%' : @%@)
     * Push (@%@:1)
               MA   LAGAAA,X2
               LCA  @%@,0+X2
     * Push (X3:3)
               MA   LOFAAA,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LJBAAA
     * Pop (X3:3)
               LCA  0+X2,X3
               MA   LPFAAA,X2
     * Pop (1)
               MA   LBGAAA,X2
     * Pop (5)
               MA   LSFAAA,X2
     LSCAAA    NOP  
               BCE  LRCAAA,RF,R
     * EndBlock (LSCAAA:LRCAAA)
     * ***********************

               B    LEDAAA
     LDDAAA    NOP  
     * IfStatement if((c == 'C') then (LTCAAA:LRCAAA) else if((c == 'S') then (LUCAAA:LRCAAA) else if((c == 'D') then (LVCAAA:LRCAAA) else (LWCAAA:LRCAAA))))
     * EqualExpression (c == 'C')
     * VariableExpression (c : 7+X3)
     * Push (7+X3:1)
               MA   LAGAAA,X2
               LCA  7+X3,0+X2
     * ConstantExpression ('C' : @C@)
     * Push (@C@:1)
               MA   LAGAAA,X2
               LCA  @C@,0+X2
               C    0+X2,15999+X2
     * Pop (1)
               MA   LBGAAA,X2
     * Pop (1)
               MA   LBGAAA,X2
     * Push (LCGAAA:5)
               MA   LRFAAA,X2
               LCA  LCGAAA,0+X2
               BE   LDHAAA
               B    LEHAAA
     LDHAAA    MCW  LQFAAA,0+X2
     LEHAAA    NOP  
               MCS  0+X2,0+X2
     * Pop (5)
               MA   LSFAAA,X2
               BCE  LBDAAA,5+X2, 

     * ***********************
     * BeginBlock (LTCAAA:LRCAAA)
     * FunctionCallExpr putchar(( *(arg--) ))
     * Push (5)
               MA   LRFAAA,X2
     * DereferenceExpression ( *(arg--) )
     * PostDecrement (arg--)
     * Push (LWGAAA:3)
               MA   LOFAAA,X2
               LCA  LWGAAA,0+X2
               MA   X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Push (0+X1:3)
               MA   LOFAAA,X2
               LCA  0+X1,0+X2
               MA   LBGAAA,0+X1
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Push (0+X1:1)
               MA   LAGAAA,X2
               LCA  0+X1,0+X2
     * Push (X3:3)
               MA   LOFAAA,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LJBAAA
     * Pop (X3:3)
               LCA  0+X2,X3
               MA   LPFAAA,X2
     * Pop (1)
               MA   LBGAAA,X2
     * Pop (5)
               MA   LSFAAA,X2
     LTCAAA    NOP  
               BCE  LRCAAA,RF,R
     * EndBlock (LTCAAA:LRCAAA)
     * ***********************

               B    LCDAAA
     LBDAAA    NOP  
     * IfStatement if((c == 'S') then (LUCAAA:LRCAAA) else if((c == 'D') then (LVCAAA:LRCAAA) else (LWCAAA:LRCAAA)))
     * EqualExpression (c == 'S')
     * VariableExpression (c : 7+X3)
     * Push (7+X3:1)
               MA   LAGAAA,X2
               LCA  7+X3,0+X2
     * ConstantExpression ('S' : @S@)
     * Push (@S@:1)
               MA   LAGAAA,X2
               LCA  @S@,0+X2
               C    0+X2,15999+X2
     * Pop (1)
               MA   LBGAAA,X2
     * Pop (1)
               MA   LBGAAA,X2
     * Push (LCGAAA:5)
               MA   LRFAAA,X2
               LCA  LCGAAA,0+X2
               BE   LFHAAA
               B    LGHAAA
     LFHAAA    MCW  LQFAAA,0+X2
     LGHAAA    NOP  
               MCS  0+X2,0+X2
     * Pop (5)
               MA   LSFAAA,X2
               BCE  LZCAAA,5+X2, 

     * ***********************
     * BeginBlock (LUCAAA:LRCAAA)
     * FunctionCallExpr puts(( *((**char) arg) ))
     * Push (5)
               MA   LRFAAA,X2
     * DereferenceExpression ( *((**char) arg) )
     * VariableExpression (arg : 6+X3)
     * Push (6+X3:3)
               MA   LOFAAA,X2
               LCA  6+X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Push (0+X1:3)
               MA   LOFAAA,X2
               LCA  0+X1,0+X2
     * Push (X3:3)
               MA   LOFAAA,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LUBAAA
     * Pop (X3:3)
               LCA  0+X2,X3
               MA   LPFAAA,X2
     * Pop (3)
               MA   LPFAAA,X2
     * Pop (5)
               MA   LSFAAA,X2
     * Assignment (arg = (arg + 15997))
     * Addition (arg + 15997)
     * VariableExpression (arg : 6+X3)
     * Push (6+X3:3)
               MA   LOFAAA,X2
               LCA  6+X3,0+X2
     * ConstantExpression (15997 : LPFAAA)
     * Push (LPFAAA:3)
               MA   LOFAAA,X2
               LCA  LPFAAA,0+X2
               MA   0+X2,15997+X2
     * Pop (3)
               MA   LPFAAA,X2
     * Push (LWGAAA:3)
               MA   LOFAAA,X2
               LCA  LWGAAA,0+X2
               MA   X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:3)
               LCA  0+X2,0+X1
               MA   LPFAAA,X2
     LUCAAA    NOP  
               BCE  LRCAAA,RF,R
     * EndBlock (LUCAAA:LRCAAA)
     * ***********************

               B    LADAAA
     LZCAAA    NOP  
     * IfStatement if((c == 'D') then (LVCAAA:LRCAAA) else (LWCAAA:LRCAAA))
     * EqualExpression (c == 'D')
     * VariableExpression (c : 7+X3)
     * Push (7+X3:1)
               MA   LAGAAA,X2
               LCA  7+X3,0+X2
     * ConstantExpression ('D' : @D@)
     * Push (@D@:1)
               MA   LAGAAA,X2
               LCA  @D@,0+X2
               C    0+X2,15999+X2
     * Pop (1)
               MA   LBGAAA,X2
     * Pop (1)
               MA   LBGAAA,X2
     * Push (LCGAAA:5)
               MA   LRFAAA,X2
               LCA  LCGAAA,0+X2
               BE   LHHAAA
               B    LIHAAA
     LHHAAA    MCW  LQFAAA,0+X2
     LIHAAA    NOP  
               MCS  0+X2,0+X2
     * Pop (5)
               MA   LSFAAA,X2
               BCE  LXCAAA,5+X2, 

     * ***********************
     * BeginBlock (LVCAAA:LRCAAA)
               MA   LVGAAA,X2
     * FunctionCallExpr itoa(( *((*int) arg) ), a, 10)
     * Push (3)
               MA   LOFAAA,X2
     * ConstantExpression (10 : LJHAAA)
     * Push (LJHAAA:5)
               MA   LRFAAA,X2
               LCA  LJHAAA,0+X2
     * ArrayNameExpresssion(a:char [7])
     * Push (LLFAAA:3)
               MA   LOFAAA,X2
               LCA  LLFAAA,0+X2
               MA   X3,0+X2
     * DereferenceExpression ( *((*int) arg) )
     * VariableExpression (arg : 6+X3)
     * Push (6+X3:3)
               MA   LOFAAA,X2
               LCA  6+X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Push (0+X1:5)
               MA   LRFAAA,X2
               LCA  0+X1,0+X2
     * Push (X3:3)
               MA   LOFAAA,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LXAAAA
     * Pop (X3:3)
               LCA  0+X2,X3
               MA   LPFAAA,X2
     * Pop (5)
               MA   LSFAAA,X2
     * Pop (3)
               MA   LPFAAA,X2
     * Pop (5)
               MA   LSFAAA,X2
     * Pop (3)
               MA   LPFAAA,X2
     * FunctionCallExpr puts(a)
     * Push (5)
               MA   LRFAAA,X2
     * ArrayNameExpresssion(a:char [7])
     * Push (LLFAAA:3)
               MA   LOFAAA,X2
               LCA  LLFAAA,0+X2
               MA   X3,0+X2
     * Push (X3:3)
               MA   LOFAAA,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LUBAAA
     * Pop (X3:3)
               LCA  0+X2,X3
               MA   LPFAAA,X2
     * Pop (3)
               MA   LPFAAA,X2
     * Pop (5)
               MA   LSFAAA,X2
     * Assignment (arg = (arg + 15995))
     * Addition (arg + 15995)
     * VariableExpression (arg : 6+X3)
     * Push (6+X3:3)
               MA   LOFAAA,X2
               LCA  6+X3,0+X2
     * ConstantExpression (15995 : LSFAAA)
     * Push (LSFAAA:3)
               MA   LOFAAA,X2
               LCA  LSFAAA,0+X2
               MA   0+X2,15997+X2
     * Pop (3)
               MA   LPFAAA,X2
     * Push (LWGAAA:3)
               MA   LOFAAA,X2
               LCA  LWGAAA,0+X2
               MA   X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:3)
               LCA  0+X2,0+X1
               MA   LPFAAA,X2
     LVCAAA    NOP  
               MA   LKHAAA,X2
               BCE  LRCAAA,RF,R
     * EndBlock (LVCAAA:LRCAAA)
     * ***********************

               B    LYCAAA
     LXCAAA    NOP  

     * ***********************
     * BeginBlock (LWCAAA:LRCAAA)
     * set the return flag, so we know do deallocate our stack
               MCW  @R@,RF
     * and branch
               B    LWCAAA
     LWCAAA    NOP  
               BCE  LRCAAA,RF,R
     * EndBlock (LWCAAA:LRCAAA)
     * ***********************

     LYCAAA    NOP  
     LADAAA    NOP  
     LCDAAA    NOP  
     LEDAAA    NOP  
     LRCAAA    NOP  
               BCE  LPCAAA,RF,R
     * EndBlock (LRCAAA:LPCAAA)
     * ***********************

     LGDAAA    NOP  
     LPCAAA    NOP  
               BCE  LOCAAA,RF,R
     * EndBlock (LPCAAA:LOCAAA)
     * ***********************

               B    LHDAAA
     LIDAAA    NOP  
     LOCAAA    NOP  
               MA   LKHAAA,X2
               MCW  @ @,RF
     * EndBlock (LOCAAA:null)
     * ***********************

               LCA  3+X3,X1
               B    0+X1

     * **********************************************************************
     * FunctionDefinition(strcpy)
     * **********************************************************************
     LJAAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3

     * ***********************
     * BeginBlock (LKAAAA:null)
               MA   LOFAAA,X2
     * WhileStatement (((( *(dest++) ) = ( *(src++) )) != '\0')) retree.statement.EmptyStatement@7d4bf534 top:LLAAAA bottom:LMAAAA)
     LLAAAA    NOP  
     * NotEqualExpression ((( *(dest++) ) = ( *(src++) )) != '\0')
     * Assignment (( *(dest++) ) = ( *(src++) ))
     * DereferenceExpression ( *(src++) )
     * PostIncrement (src++)
     * Push (LNHAAA:3)
               MA   LOFAAA,X2
               LCA  LNHAAA,0+X2
               MA   X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Push (0+X1:3)
               MA   LOFAAA,X2
               LCA  0+X1,0+X2
               MA   LAGAAA,0+X1
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Push (0+X1:1)
               MA   LAGAAA,X2
               LCA  0+X1,0+X2
     * PostIncrement (dest++)
     * Push (LPFAAA:3)
               MA   LOFAAA,X2
               LCA  LPFAAA,0+X2
               MA   X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Push (0+X1:3)
               MA   LOFAAA,X2
               LCA  0+X1,0+X2
               MA   LAGAAA,0+X1
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
               LCA  0+X2,0+X1
     * ConstantExpression ('\0' : EOS)
     * Push (EOS:1)
               MA   LAGAAA,X2
               LCA  EOS,0+X2
               C    0+X2,15999+X2
     * Pop (1)
               MA   LBGAAA,X2
     * Pop (1)
               MA   LBGAAA,X2
     * Push (LQFAAA:5)
               MA   LRFAAA,X2
               LCA  LQFAAA,0+X2
               BE   LLHAAA
               B    LMHAAA
     LLHAAA    MCW  LCGAAA,0+X2
     LMHAAA    NOP  
               MCS  0+X2,0+X2
     * Pop (5)
               MA   LSFAAA,X2
               BCE  LMAAAA,5+X2, 
               B    LLAAAA
     LMAAAA    NOP  
     LKAAAA    NOP  
               MA   LPFAAA,X2
               MCW  @ @,RF
     * EndBlock (LKAAAA:null)
     * ***********************

               LCA  3+X3,X1
               B    0+X1

     * **********************************************************************
     * FunctionDefinition(main)
     * **********************************************************************
     LTDAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3

     * ***********************
     * BeginBlock (LUDAAA:null)
               MA   LOHAAA,X2
     * DoWhileStatement ((i != 1)) (LVDAAA:LUDAAA) top:LWDAAA bottom:LXDAAA)
     LWDAAA    NOP  

     * ***********************
     * BeginBlock (LVDAAA:LUDAAA)
     * Assignment (i = 1)
     * ConstantExpression (1 : LQFAAA)
     * Push (LQFAAA:5)
               MA   LRFAAA,X2
               LCA  LQFAAA,0+X2
     * Push (LOHAAA:3)
               MA   LOFAAA,X2
               LCA  LOHAAA,0+X2
               MA   X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:5)
               LCA  0+X2,0+X1
               MA   LSFAAA,X2
     LVDAAA    NOP  
               BCE  LUDAAA,RF,R
     * EndBlock (LVDAAA:LUDAAA)
     * ***********************

     * NotEqualExpression (i != 1)
     * VariableExpression (i : 218+X3)
     * Push (218+X3:5)
               MA   LRFAAA,X2
               LCA  218+X3,0+X2
               B    LFGAAA
     * ConstantExpression (1 : LQFAAA)
     * Push (LQFAAA:5)
               MA   LRFAAA,X2
               LCA  LQFAAA,0+X2
               B    LFGAAA
               C    0+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
     * Pop (5)
               MA   LSFAAA,X2
     * Push (LQFAAA:5)
               MA   LRFAAA,X2
               LCA  LQFAAA,0+X2
               BE   LPHAAA
               B    LQHAAA
     LPHAAA    MCW  LCGAAA,0+X2
     LQHAAA    NOP  
               MCS  0+X2,0+X2
     * Pop (5)
               MA   LSFAAA,X2
               BCE  LXDAAA,5+X2, 
               B    LWDAAA
     LXDAAA    NOP  
     * ForStatement ((i = 0); (i <= 20); (i++)) (LYDAAA:LUDAAA) top:LZDAAA bottom:LAEAAA continue:LBEAAA)
     * Assignment (i = 0)
     * ConstantExpression (0 : LCGAAA)
     * Push (LCGAAA:5)
               MA   LRFAAA,X2
               LCA  LCGAAA,0+X2
     * Push (LOHAAA:3)
               MA   LOFAAA,X2
               LCA  LOHAAA,0+X2
               MA   X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:5)
               LCA  0+X2,0+X1
               MA   LSFAAA,X2
     LZDAAA    NOP  
     * LessThanOrEqualExpression (i <= 20)
     * VariableExpression (i : 218+X3)
     * Push (218+X3:5)
               MA   LRFAAA,X2
               LCA  218+X3,0+X2
               B    LFGAAA
     * ConstantExpression (20 : LRGAAA)
     * Push (LRGAAA:5)
               MA   LRFAAA,X2
               LCA  LRGAAA,0+X2
               B    LFGAAA
               C    0+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
               MCW  LQFAAA,0+X2
               BH   LRHAAA
               B    LSHAAA
     LRHAAA    MCW  LCGAAA,0+X2
     LSHAAA    NOP  
               MCS  0+X2,0+X2
     * Pop (5)
               MA   LSFAAA,X2
               BCE  LAEAAA,5+X2, 

     * ***********************
     * BeginBlock (LYDAAA:LUDAAA)
     * Assignment ((x[i]) = ((i == 1) ? 1 : 0))
     * TernaryExpression ((i == 1) ? 1 : 0)
     * EqualExpression (i == 1)
     * VariableExpression (i : 218+X3)
     * Push (218+X3:5)
               MA   LRFAAA,X2
               LCA  218+X3,0+X2
               B    LFGAAA
     * ConstantExpression (1 : LQFAAA)
     * Push (LQFAAA:5)
               MA   LRFAAA,X2
               LCA  LQFAAA,0+X2
               B    LFGAAA
               C    0+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
     * Pop (5)
               MA   LSFAAA,X2
     * Push (LCGAAA:5)
               MA   LRFAAA,X2
               LCA  LCGAAA,0+X2
               BE   LVHAAA
               B    LWHAAA
     LVHAAA    MCW  LQFAAA,0+X2
     LWHAAA    NOP  
               MCS  0+X2,0+X2
     * Pop (5)
               MA   LSFAAA,X2
               BCE  LTHAAA,5+X2, 
     * ConstantExpression (1 : LQFAAA)
     * Push (LQFAAA:5)
               MA   LRFAAA,X2
               LCA  LQFAAA,0+X2
               B    LUHAAA
     LTHAAA    NOP  
     * ConstantExpression (0 : LCGAAA)
     * Push (LCGAAA:5)
               MA   LRFAAA,X2
               LCA  LCGAAA,0+X2
     LUHAAA    NOP  
     * ArrayNameExpresssion(x:int [21])
     * Push (LLFAAA:3)
               MA   LOFAAA,X2
               LCA  LLFAAA,0+X2
               MA   X3,0+X2
     * VariableExpression (i : 218+X3)
     * Push (218+X3:5)
               MA   LRFAAA,X2
               LCA  218+X3,0+X2
     * raw index on the stack
     * Push (LNGAAA:5)
               MA   LRFAAA,X2
               LCA  LNGAAA,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
     * STACK TOP IS NOW ARRAY INDEX
               B    LTFAAA
               MA   0+X2,15997+X2
     * Pop (3)
               MA   LPFAAA,X2
     * STACK top is location in array now.
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:5)
               LCA  0+X2,0+X1
               MA   LSFAAA,X2
     * Assignment ((y[i]) = 0)
     * ConstantExpression (0 : LCGAAA)
     * Push (LCGAAA:5)
               MA   LRFAAA,X2
               LCA  LCGAAA,0+X2
     * ArrayNameExpresssion(y:int [21])
     * Push (LXHAAA:3)
               MA   LOFAAA,X2
               LCA  LXHAAA,0+X2
               MA   X3,0+X2
     * VariableExpression (i : 218+X3)
     * Push (218+X3:5)
               MA   LRFAAA,X2
               LCA  218+X3,0+X2
     * raw index on the stack
     * Push (LNGAAA:5)
               MA   LRFAAA,X2
               LCA  LNGAAA,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
     * STACK TOP IS NOW ARRAY INDEX
               B    LTFAAA
               MA   0+X2,15997+X2
     * Pop (3)
               MA   LPFAAA,X2
     * STACK top is location in array now.
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:5)
               LCA  0+X2,0+X1
               MA   LSFAAA,X2
     LYDAAA    NOP  
               BCE  LUDAAA,RF,R
     * EndBlock (LYDAAA:LUDAAA)
     * ***********************

     LBEAAA    NOP  
     * PostIncrement (i++)
     * Push (LOHAAA:3)
               MA   LOFAAA,X2
               LCA  LOHAAA,0+X2
               MA   X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
               A    LQFAAA,0+X1
               B    LZDAAA
     LAEAAA    NOP  
     * FunctionCallExpr printf("Pascal Triangle with %d iterations\n\n", 20)
     * Push (5)
               MA   LRFAAA,X2
     * ConstantExpression (20 : LRGAAA)
     * Push (LRGAAA:5)
               MA   LRFAAA,X2
               LCA  LRGAAA,0+X2
     * ArrayNameExpresssion("Pascal Triangle with %d iterations\n\n":char [37])
     * Push (LYHAAA:3)
               MA   LOFAAA,X2
               LCA  LYHAAA,0+X2
     * Push (X3:3)
               MA   LOFAAA,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LNCAAA
     * Pop (X3:3)
               LCA  0+X2,X3
               MA   LPFAAA,X2
     * Pop (3)
               MA   LPFAAA,X2
     * Pop (5)
               MA   LSFAAA,X2
     * Pop (5)
               MA   LSFAAA,X2
     * FunctionCallExpr pascals(x, y, 0)
     * Push (5)
               MA   LRFAAA,X2
     * ConstantExpression (0 : LCGAAA)
     * Push (LCGAAA:5)
               MA   LRFAAA,X2
               LCA  LCGAAA,0+X2
     * ArrayNameExpresssion(y:int [21])
     * Push (LXHAAA:3)
               MA   LOFAAA,X2
               LCA  LXHAAA,0+X2
               MA   X3,0+X2
     * ArrayNameExpresssion(x:int [21])
     * Push (LLFAAA:3)
               MA   LOFAAA,X2
               LCA  LLFAAA,0+X2
               MA   X3,0+X2
     * Push (X3:3)
               MA   LOFAAA,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LNDAAA
     * Pop (X3:3)
               LCA  0+X2,X3
               MA   LPFAAA,X2
     * Pop (3)
               MA   LPFAAA,X2
     * Pop (3)
               MA   LPFAAA,X2
     * Pop (5)
               MA   LSFAAA,X2
     * Pop (5)
               MA   LSFAAA,X2
     * FunctionCallExpr printf("\nDone.\n")
     * Push (5)
               MA   LRFAAA,X2
     * ArrayNameExpresssion("\nDone.\n":char [8])
     * Push (LZHAAA:3)
               MA   LOFAAA,X2
               LCA  LZHAAA,0+X2
     * Push (X3:3)
               MA   LOFAAA,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LNCAAA
     * Pop (X3:3)
               LCA  0+X2,X3
               MA   LPFAAA,X2
     * Pop (3)
               MA   LPFAAA,X2
     * Pop (5)
               MA   LSFAAA,X2
     LUDAAA    NOP  
               MA   LAIAAA,X2
               MCW  @ @,RF
     * EndBlock (LUDAAA:null)
     * ***********************

               LCA  3+X3,X1
               B    0+X1

     * **********************************************************************
     * FunctionDefinition(puts)
     * **********************************************************************
     LUBAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3

     * ***********************
     * BeginBlock (LVBAAA:null)
               MA   LOFAAA,X2
     * WhileStatement ((( *s ) != '\0')) (LWBAAA:LVBAAA) top:LXBAAA bottom:LYBAAA)
     LXBAAA    NOP  
     * NotEqualExpression (( *s ) != '\0')
     * DereferenceExpression ( *s )
     * VariableExpression (s : 15997+X3)
     * Push (15997+X3:3)
               MA   LOFAAA,X2
               LCA  15997+X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Push (0+X1:1)
               MA   LAGAAA,X2
               LCA  0+X1,0+X2
     * ConstantExpression ('\0' : EOS)
     * Push (EOS:1)
               MA   LAGAAA,X2
               LCA  EOS,0+X2
               C    0+X2,15999+X2
     * Pop (1)
               MA   LBGAAA,X2
     * Pop (1)
               MA   LBGAAA,X2
     * Push (LQFAAA:5)
               MA   LRFAAA,X2
               LCA  LQFAAA,0+X2
               BE   LBIAAA
               B    LCIAAA
     LBIAAA    MCW  LCGAAA,0+X2
     LCIAAA    NOP  
               MCS  0+X2,0+X2
     * Pop (5)
               MA   LSFAAA,X2
               BCE  LYBAAA,5+X2, 

     * ***********************
     * BeginBlock (LWBAAA:LVBAAA)
     * FunctionCallExpr putchar(( *(s++) ))
     * Push (5)
               MA   LRFAAA,X2
     * DereferenceExpression ( *(s++) )
     * PostIncrement (s++)
     * Push (LPFAAA:3)
               MA   LOFAAA,X2
               LCA  LPFAAA,0+X2
               MA   X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Push (0+X1:3)
               MA   LOFAAA,X2
               LCA  0+X1,0+X2
               MA   LAGAAA,0+X1
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Push (0+X1:1)
               MA   LAGAAA,X2
               LCA  0+X1,0+X2
     * Push (X3:3)
               MA   LOFAAA,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LJBAAA
     * Pop (X3:3)
               LCA  0+X2,X3
               MA   LPFAAA,X2
     * Pop (1)
               MA   LBGAAA,X2
     * Pop (5)
               MA   LSFAAA,X2
     LWBAAA    NOP  
               BCE  LVBAAA,RF,R
     * EndBlock (LWBAAA:LVBAAA)
     * ***********************

               B    LXBAAA
     LYBAAA    NOP  
     LVBAAA    NOP  
               MA   LPFAAA,X2
               MCW  @ @,RF
     * EndBlock (LVBAAA:null)
     * ***********************

               LCA  3+X3,X1
               B    0+X1

     * **********************************************************************
     * FunctionDefinition(putchar)
     * **********************************************************************
     LJBAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3

     * ***********************
     * BeginBlock (LKBAAA:null)
               MA   LOFAAA,X2
     * IfStatement if((c != '\n') then (LLBAAA:LKBAAA) else (LMBAAA:LKBAAA))
     * NotEqualExpression (c != '\n')
     * VariableExpression (c : 15997+X3)
     * Push (15997+X3:1)
               MA   LAGAAA,X2
               LCA  15997+X3,0+X2
     * ConstantExpression ('\n' : EOL)
     * Push (EOL:1)
               MA   LAGAAA,X2
               LCA  EOL,0+X2
               C    0+X2,15999+X2
     * Pop (1)
               MA   LBGAAA,X2
     * Pop (1)
               MA   LBGAAA,X2
     * Push (LQFAAA:5)
               MA   LRFAAA,X2
               LCA  LQFAAA,0+X2
               BE   LDIAAA
               B    LEIAAA
     LDIAAA    MCW  LCGAAA,0+X2
     LEIAAA    NOP  
               MCS  0+X2,0+X2
     * Pop (5)
               MA   LSFAAA,X2
               BCE  LQBAAA,5+X2, 

     * ***********************
     * BeginBlock (LLBAAA:LKBAAA)
     * Assignment (( *(__putchar_pos++) ) = c)
     * VariableExpression (c : 15997+X3)
     * Push (15997+X3:1)
               MA   LAGAAA,X2
               LCA  15997+X3,0+X2
     * PostIncrement (__putchar_pos++)
     * Push (LFIAAA:3)
               MA   LOFAAA,X2
               LCA  LFIAAA,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Push (0+X1:3)
               MA   LOFAAA,X2
               LCA  0+X1,0+X2
               MA   LAGAAA,0+X1
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:1)
               LCA  0+X2,0+X1
               MA   LBGAAA,X2
     LLBAAA    NOP  
               BCE  LKBAAA,RF,R
     * EndBlock (LLBAAA:LKBAAA)
     * ***********************

               B    LRBAAA
     LQBAAA    NOP  

     * ***********************
     * BeginBlock (LMBAAA:LKBAAA)
     * WhileStatement ((((int) __putchar_last) >= ((int) __putchar_pos))) (LNBAAA:LMBAAA) top:LOBAAA bottom:LPBAAA)
     LOBAAA    NOP  
     * GreaterThanOrEqualExpression((((int) __putchar_last) >= ((int) __putchar_pos))
     * StaticVariableExpression (__putchar_last : 5028)
     * Push (5028:3)
               MA   LOFAAA,X2
               LCA  5028,0+X2
               B    LGIAAA
               B    LFGAAA
     * StaticVariableExpression (__putchar_pos : 5025)
     * Push (5025:3)
               MA   LOFAAA,X2
               LCA  5025,0+X2
               B    LGIAAA
               B    LFGAAA
               C    0+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
               MCW  LQFAAA,0+X2
               BL   LPIAAA
               B    LQIAAA
     LPIAAA    MCW  LCGAAA,0+X2
     LQIAAA    NOP  
               MCS  0+X2,0+X2
     * Pop (5)
               MA   LSFAAA,X2
               BCE  LPBAAA,5+X2, 

     * ***********************
     * BeginBlock (LNBAAA:LMBAAA)
     * Assignment (( *(__putchar_last--) ) = ' ')
     * ConstantExpression (' ' : @ @)
     * Push (@ @:1)
               MA   LAGAAA,X2
               LCA  @ @,0+X2
     * PostDecrement (__putchar_last--)
     * Push (LRIAAA:3)
               MA   LOFAAA,X2
               LCA  LRIAAA,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Push (0+X1:3)
               MA   LOFAAA,X2
               LCA  0+X1,0+X2
               MA   LBGAAA,0+X1
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:1)
               LCA  0+X2,0+X1
               MA   LBGAAA,X2
     LNBAAA    NOP  
               BCE  LMBAAA,RF,R
     * EndBlock (LNBAAA:LMBAAA)
     * ***********************

               B    LOBAAA
     LPBAAA    NOP  
     * Assignment (__putchar_last = __putchar_pos)
     * StaticVariableExpression (__putchar_pos : 5025)
     * Push (5025:3)
               MA   LOFAAA,X2
               LCA  5025,0+X2
     * Push (LRIAAA:3)
               MA   LOFAAA,X2
               LCA  LRIAAA,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:3)
               LCA  0+X2,0+X1
               MA   LPFAAA,X2
     * Assignment (__putchar_pos = 201)
     * ConstantExpression (201 : LDEAAA)
     * Push (LDEAAA:3)
               MA   LOFAAA,X2
               LCA  LDEAAA,0+X2
     * Push (LFIAAA:3)
               MA   LOFAAA,X2
               LCA  LFIAAA,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:3)
               LCA  0+X2,0+X1
               MA   LPFAAA,X2
     * Start asm block
               W    
     * End asm block
     LMBAAA    NOP  
               BCE  LKBAAA,RF,R
     * EndBlock (LMBAAA:LKBAAA)
     * ***********************

     LRBAAA    NOP  
     * IfStatement if((__putchar_pos == 333) then (LSBAAA:LKBAAA))
     * EqualExpression (__putchar_pos == 333)
     * StaticVariableExpression (__putchar_pos : 5025)
     * Push (5025:3)
               MA   LOFAAA,X2
               LCA  5025,0+X2
     * ConstantExpression (333 : LUIAAA)
     * Push (LUIAAA:3)
               MA   LOFAAA,X2
               LCA  LUIAAA,0+X2
               C    0+X2,15997+X2
     * Pop (3)
               MA   LPFAAA,X2
     * Pop (3)
               MA   LPFAAA,X2
     * Push (LCGAAA:5)
               MA   LRFAAA,X2
               LCA  LCGAAA,0+X2
               BE   LSIAAA
               B    LTIAAA
     LSIAAA    MCW  LQFAAA,0+X2
     LTIAAA    NOP  
               MCS  0+X2,0+X2
     * Pop (5)
               MA   LSFAAA,X2
               BCE  LTBAAA,5+X2, 

     * ***********************
     * BeginBlock (LSBAAA:LKBAAA)
     * Assignment (__putchar_last = __putchar_pos)
     * StaticVariableExpression (__putchar_pos : 5025)
     * Push (5025:3)
               MA   LOFAAA,X2
               LCA  5025,0+X2
     * Push (LRIAAA:3)
               MA   LOFAAA,X2
               LCA  LRIAAA,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:3)
               LCA  0+X2,0+X1
               MA   LPFAAA,X2
     * Assignment (__putchar_pos = 201)
     * ConstantExpression (201 : LDEAAA)
     * Push (LDEAAA:3)
               MA   LOFAAA,X2
               LCA  LDEAAA,0+X2
     * Push (LFIAAA:3)
               MA   LOFAAA,X2
               LCA  LFIAAA,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:3)
               LCA  0+X2,0+X1
               MA   LPFAAA,X2
     * Start asm block
               W    
     * End asm block
     LSBAAA    NOP  
               BCE  LKBAAA,RF,R
     * EndBlock (LSBAAA:LKBAAA)
     * ***********************

     LTBAAA    NOP  
     LKBAAA    NOP  
               MA   LPFAAA,X2
               MCW  @ @,RF
     * EndBlock (LKBAAA:null)
     * ***********************

               LCA  3+X3,X1
               B    0+X1

     * **********************************************************************
     * FunctionDefinition(genRand)
     * **********************************************************************
     LBAAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3

     * ***********************
     * BeginBlock (LCAAAA:null)
               MA   LOFAAA,X2
     * Assignment (seed = (((42 * seed) + 19) % 100000))
     * ModuloExpression (((42 * seed) + 19) % 100000)
     * ConstantExpression (100000 : LVIAAA)
     * Push (LVIAAA:5)
               MA   LRFAAA,X2
               LCA  LVIAAA,0+X2
     * Addition ((42 * seed) + 19)
     * Multiplication (42 * seed)
     * ConstantExpression (42 : LWIAAA)
     * Push (LWIAAA:5)
               MA   LRFAAA,X2
               LCA  LWIAAA,0+X2
     * StaticVariableExpression (seed : 5005)
     * Push (5005:5)
               MA   LRFAAA,X2
               LCA  5005,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
     * ConstantExpression (19 : LXIAAA)
     * Push (LXIAAA:5)
               MA   LRFAAA,X2
               LCA  LXIAAA,0+X2
               A    0+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
               B    LYIAAA
     * Pop (5)
               MA   LSFAAA,X2
     * Push (LEJAAA:3)
               MA   LOFAAA,X2
               LCA  LEJAAA,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:5)
               LCA  0+X2,0+X1
               MA   LSFAAA,X2
     * StaticVariableExpression (seed : 5005)
     * Push (5005:5)
               MA   LRFAAA,X2
               LCA  5005,0+X2
     * Pop (15997+X3:5)
               LCA  0+X2,15997+X3
               MA   LSFAAA,X2
     * set the return flag, so we know do deallocate our stack
               MCW  @R@,RF
     * and branch
               B    LCAAAA
     LCAAAA    NOP  
               MA   LPFAAA,X2
               MCW  @ @,RF
     * EndBlock (LCAAAA:null)
     * ***********************

               LCA  3+X3,X1
               B    0+X1

     * **********************************************************************
     * FunctionDefinition(itoa)
     * **********************************************************************
     LXAAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3

     * ***********************
     * BeginBlock (LYAAAA:null)
               LCA  LFJAAA,9+X3
               LCA  LQFAAA,14+X3
               MA   LEGAAA,X2
     * Assignment (start = str)
     * VariableExpression (str : 15992+X3)
     * Push (15992+X3:3)
               MA   LOFAAA,X2
               LCA  15992+X3,0+X2
     * Push (LWGAAA:3)
               MA   LOFAAA,X2
               LCA  LWGAAA,0+X2
               MA   X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:3)
               LCA  0+X2,0+X1
               MA   LPFAAA,X2
     * IfStatement if((value < 0) then (LZAAAA:LYAAAA) else if((value == 0) then (LABAAA:LYAAAA)))
     * LessThanExpression (value < 0)
     * VariableExpression (value : 15997+X3)
     * Push (15997+X3:5)
               MA   LRFAAA,X2
               LCA  15997+X3,0+X2
               B    LFGAAA
     * ConstantExpression (0 : LCGAAA)
     * Push (LCGAAA:5)
               MA   LRFAAA,X2
               LCA  LCGAAA,0+X2
               B    LFGAAA
               C    0+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
               MCW  LCGAAA,0+X2
               BL   LGJAAA
               B    LHJAAA
     LGJAAA    MCW  LQFAAA,0+X2
     LHJAAA    NOP  
               MCS  0+X2,0+X2
     * Pop (5)
               MA   LSFAAA,X2
               BCE  LCBAAA,5+X2, 

     * ***********************
     * BeginBlock (LZAAAA:LYAAAA)
     * Assignment (( *(str++) ) = '-')
     * ConstantExpression ('-' : @-@)
     * Push (@-@:1)
               MA   LAGAAA,X2
               LCA  @-@,0+X2
     * PostIncrement (str++)
     * Push (LDGAAA:3)
               MA   LOFAAA,X2
               LCA  LDGAAA,0+X2
               MA   X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Push (0+X1:3)
               MA   LOFAAA,X2
               LCA  0+X1,0+X2
               MA   LAGAAA,0+X1
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:1)
               LCA  0+X2,0+X1
               MA   LBGAAA,X2
     * Assignment (value = (-value))
     * NegExpression (-value)
     * VariableExpression (value : 15997+X3)
     * Push (15997+X3:5)
               MA   LRFAAA,X2
               LCA  15997+X3,0+X2
               ZS   0+X2
               B    LFGAAA
     * Push (LPFAAA:3)
               MA   LOFAAA,X2
               LCA  LPFAAA,0+X2
               MA   X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:5)
               LCA  0+X2,0+X1
               MA   LSFAAA,X2
     LZAAAA    NOP  
               BCE  LYAAAA,RF,R
     * EndBlock (LZAAAA:LYAAAA)
     * ***********************

               B    LDBAAA
     LCBAAA    NOP  
     * IfStatement if((value == 0) then (LABAAA:LYAAAA))
     * EqualExpression (value == 0)
     * VariableExpression (value : 15997+X3)
     * Push (15997+X3:5)
               MA   LRFAAA,X2
               LCA  15997+X3,0+X2
               B    LFGAAA
     * ConstantExpression (0 : LCGAAA)
     * Push (LCGAAA:5)
               MA   LRFAAA,X2
               LCA  LCGAAA,0+X2
               B    LFGAAA
               C    0+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
     * Pop (5)
               MA   LSFAAA,X2
     * Push (LCGAAA:5)
               MA   LRFAAA,X2
               LCA  LCGAAA,0+X2
               BE   LJJAAA
               B    LKJAAA
     LJJAAA    MCW  LQFAAA,0+X2
     LKJAAA    NOP  
               MCS  0+X2,0+X2
     * Pop (5)
               MA   LSFAAA,X2
               BCE  LBBAAA,5+X2, 

     * ***********************
     * BeginBlock (LABAAA:LYAAAA)
     * Assignment ((str[0]) = '0')
     * ConstantExpression ('0' : @0@)
     * Push (@0@:1)
               MA   LAGAAA,X2
               LCA  @0@,0+X2
     * VariableExpression (str : 15992+X3)
     * Push (15992+X3:3)
               MA   LOFAAA,X2
               LCA  15992+X3,0+X2
     * ConstantExpression (0 : LCGAAA)
     * Push (LCGAAA:5)
               MA   LRFAAA,X2
               LCA  LCGAAA,0+X2
     * raw index on the stack
     * Push (LQFAAA:5)
               MA   LRFAAA,X2
               LCA  LQFAAA,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
     * STACK TOP IS NOW ARRAY INDEX
               B    LTFAAA
               MA   0+X2,15997+X2
     * Pop (3)
               MA   LPFAAA,X2
     * STACK top is location in array now.
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:1)
               LCA  0+X2,0+X1
               MA   LBGAAA,X2
     * Assignment ((str[1]) = '\0')
     * ConstantExpression ('\0' : EOS)
     * Push (EOS:1)
               MA   LAGAAA,X2
               LCA  EOS,0+X2
     * VariableExpression (str : 15992+X3)
     * Push (15992+X3:3)
               MA   LOFAAA,X2
               LCA  15992+X3,0+X2
     * ConstantExpression (1 : LQFAAA)
     * Push (LQFAAA:5)
               MA   LRFAAA,X2
               LCA  LQFAAA,0+X2
     * raw index on the stack
     * Push (LQFAAA:5)
               MA   LRFAAA,X2
               LCA  LQFAAA,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
     * STACK TOP IS NOW ARRAY INDEX
               B    LTFAAA
               MA   0+X2,15997+X2
     * Pop (3)
               MA   LPFAAA,X2
     * STACK top is location in array now.
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:1)
               LCA  0+X2,0+X1
               MA   LBGAAA,X2
     * VariableExpression (start : 6+X3)
     * Push (6+X3:3)
               MA   LOFAAA,X2
               LCA  6+X3,0+X2
     * Pop (15984+X3:3)
               LCA  0+X2,15984+X3
               MA   LPFAAA,X2
     * set the return flag, so we know do deallocate our stack
               MCW  @R@,RF
     * and branch
               B    LABAAA
     LABAAA    NOP  
               BCE  LYAAAA,RF,R
     * EndBlock (LABAAA:LYAAAA)
     * ***********************

     LBBAAA    NOP  
     LDBAAA    NOP  
     * WhileStatement ((exp <= (value / base))) retree.statement.ExpressionStatement@3535a92b top:LEBAAA bottom:LFBAAA)
     LEBAAA    NOP  
     * LessThanOrEqualExpression (exp <= (value / base))
     * VariableExpression (exp : 14+X3)
     * Push (14+X3:5)
               MA   LRFAAA,X2
               LCA  14+X3,0+X2
               B    LFGAAA
     * Divide (value / base)
     * VariableExpression (base : 15989+X3)
     * Push (15989+X3:5)
               MA   LRFAAA,X2
               LCA  15989+X3,0+X2
     * VariableExpression (value : 15997+X3)
     * Push (15997+X3:5)
               MA   LRFAAA,X2
               LCA  15997+X3,0+X2
               B    LYIAAA
               MCW  0+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
               B    LFGAAA
               C    0+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
               MCW  LQFAAA,0+X2
               BH   LLJAAA
               B    LMJAAA
     LLJAAA    MCW  LCGAAA,0+X2
     LMJAAA    NOP  
               MCS  0+X2,0+X2
     * Pop (5)
               MA   LSFAAA,X2
               BCE  LFBAAA,5+X2, 
     * Assignment (exp = (exp * base))
     * Multiplication (exp * base)
     * VariableExpression (exp : 14+X3)
     * Push (14+X3:5)
               MA   LRFAAA,X2
               LCA  14+X3,0+X2
     * VariableExpression (base : 15989+X3)
     * Push (15989+X3:5)
               MA   LRFAAA,X2
               LCA  15989+X3,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
     * Push (LEGAAA:3)
               MA   LOFAAA,X2
               LCA  LEGAAA,0+X2
               MA   X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:5)
               LCA  0+X2,0+X1
               MA   LSFAAA,X2
               B    LEBAAA
     LFBAAA    NOP  
     * WhileStatement (exp) (LGBAAA:LYAAAA) top:LHBAAA bottom:LIBAAA)
     LHBAAA    NOP  
     * VariableExpression (exp : 14+X3)
     * Push (14+X3:5)
               MA   LRFAAA,X2
               LCA  14+X3,0+X2
               MCS  0+X2,0+X2
     * Pop (5)
               MA   LSFAAA,X2
               BCE  LIBAAA,5+X2, 

     * ***********************
     * BeginBlock (LGBAAA:LYAAAA)
     * Assignment (( *(str++) ) = (digits[(value / exp)]))
     * SubScriptEpression (digits[(value / exp)])
     * VariableExpression (digits : 9+X3)
     * Push (9+X3:3)
               MA   LOFAAA,X2
               LCA  9+X3,0+X2
     * Divide (value / exp)
     * VariableExpression (exp : 14+X3)
     * Push (14+X3:5)
               MA   LRFAAA,X2
               LCA  14+X3,0+X2
     * VariableExpression (value : 15997+X3)
     * Push (15997+X3:5)
               MA   LRFAAA,X2
               LCA  15997+X3,0+X2
               B    LYIAAA
               MCW  0+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
     * raw index on the stack
     * Push (LQFAAA:5)
               MA   LRFAAA,X2
               LCA  LQFAAA,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
     * STACK TOP IS NOW ARRAY INDEX
               B    LTFAAA
               MA   0+X2,15997+X2
     * Pop (3)
               MA   LPFAAA,X2
     * STACK top is location in array now.
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Push (0+X1:1)
               MA   LAGAAA,X2
               LCA  0+X1,0+X2
     * PostIncrement (str++)
     * Push (LDGAAA:3)
               MA   LOFAAA,X2
               LCA  LDGAAA,0+X2
               MA   X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Push (0+X1:3)
               MA   LOFAAA,X2
               LCA  0+X1,0+X2
               MA   LAGAAA,0+X1
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:1)
               LCA  0+X2,0+X1
               MA   LBGAAA,X2
     * Assignment (value = (value % exp))
     * ModuloExpression (value % exp)
     * VariableExpression (exp : 14+X3)
     * Push (14+X3:5)
               MA   LRFAAA,X2
               LCA  14+X3,0+X2
     * VariableExpression (value : 15997+X3)
     * Push (15997+X3:5)
               MA   LRFAAA,X2
               LCA  15997+X3,0+X2
               B    LYIAAA
     * Pop (5)
               MA   LSFAAA,X2
     * Push (LPFAAA:3)
               MA   LOFAAA,X2
               LCA  LPFAAA,0+X2
               MA   X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:5)
               LCA  0+X2,0+X1
               MA   LSFAAA,X2
     * Assignment (exp = (exp / base))
     * Divide (exp / base)
     * VariableExpression (base : 15989+X3)
     * Push (15989+X3:5)
               MA   LRFAAA,X2
               LCA  15989+X3,0+X2
     * VariableExpression (exp : 14+X3)
     * Push (14+X3:5)
               MA   LRFAAA,X2
               LCA  14+X3,0+X2
               B    LYIAAA
               MCW  0+X2,15995+X2
     * Pop (5)
               MA   LSFAAA,X2
     * Push (LEGAAA:3)
               MA   LOFAAA,X2
               LCA  LEGAAA,0+X2
               MA   X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:5)
               LCA  0+X2,0+X1
               MA   LSFAAA,X2
     LGBAAA    NOP  
               BCE  LYAAAA,RF,R
     * EndBlock (LGBAAA:LYAAAA)
     * ***********************

               B    LHBAAA
     LIBAAA    NOP  
     * Assignment (( *str ) = '\0')
     * ConstantExpression ('\0' : EOS)
     * Push (EOS:1)
               MA   LAGAAA,X2
               LCA  EOS,0+X2
     * VariableExpression (str : 15992+X3)
     * Push (15992+X3:3)
               MA   LOFAAA,X2
               LCA  15992+X3,0+X2
     * Pop (X1:3)
               LCA  0+X2,X1
               MA   LPFAAA,X2
     * Pop (0+X1:1)
               LCA  0+X2,0+X1
               MA   LBGAAA,X2
     * VariableExpression (start : 6+X3)
     * Push (6+X3:3)
               MA   LOFAAA,X2
               LCA  6+X3,0+X2
     * Pop (15984+X3:3)
               LCA  0+X2,15984+X3
               MA   LPFAAA,X2
     * set the return flag, so we know do deallocate our stack
               MCW  @R@,RF
     * and branch
               B    LYAAAA
     LYAAAA    NOP  
               MA   LUGAAA,X2
               MCW  @ @,RF
     * EndBlock (LYAAAA:null)
     * ***********************

               LCA  3+X3,X1
               B    0+X1
     LFGAAA    SBR  X1
     * Normalizes the zone bits of a number, leaving either A=0B=0
     * for a positive or A=0B=1 for a negative
     * Do nothing on either no zone bits or only a b zone bit
               BWZ  LGGAAA,0+X2,2
               BWZ  LGGAAA,0+X2,K
     * else clear the zone bits, as it is positive
               MZ   @ @,0+X2
     LGGAAA    B    0+X1
    ****************************************************************  
    ** DIVISION SNIPPET                                           **
    ****************************************************************  
     
     LYIAAA    SBR  LZIAAA+3           * SETUP RETURN ADDRESS
     * POP DIVIDEND
               MCW  0+X2, LAJAAA
               SBR  X2, 15995+X2

     * POP DIVISOR
               MCW  0+X2, LBJAAA
               SBR  X2, 15995+X2


               B    *+17
               
               DCW  @00000@                
               DC   @00000000000@        

               ZA   LAJAAA, *-7         * PUT DIVIDEND INTO WORKING BL
               D    LBJAAA, *-19        * DIVIDE
               MZ   *-22, *-21          * KILL THE ZONE BIT
               MZ   *-29, *-34          * KILL THE ZONE BIT
               MCW  *-41, LCJAAA        * PICK UP ANSWER
               SW   *-44                * SO I CAN PICKUP REMAINDER
               MCW  *-46, LDJAAA        * GET REMAINDER
               CW   *-55                * CLEAR THE WM
               MZ   LCJAAA-1, LCJAAA    * CLEANUP QUOTIENT BITZONE
               MZ   LDJAAA-1, LDJAAA    * CLEANUP REMAINDER BITZONE
               
     * PUSH REMAINDER
               SBR  X2, 5+X2
               SW   15996+X2
               MCW  LDJAAA, 0+X2
               
     * PUSH QUOTIENT
               SBR  X2, 5+X2
               SW   15996+X2
               MCW  LCJAAA, 0+X2

     LZIAAA    B    000                 * JUMP BACK
               
     LBJAAA    DCW  00000               * DIVISOR
     LAJAAA    DCW  00000               * DIVIDEND
     LCJAAA    DCW  00000               * QUOTIENT
     LDJAAA    DCW  00000               * REMAINDER
     LTFAAA    SBR  X1
     * Casts a 5-digit number to a 3-digit address
     * make a copy of the top of the stack
               SW   15998+X2
               LCA  0+X2,3+X2
               CW   15998+X2
     * zero out the zone bits of our copy
               MZ   @0@,3+X2
               MZ   @0@,2+X2
               MZ   @0@,1+X2
     * set the low-order digit's zone bits
               C    @04000@,0+X2
               BL   LWFAAA
               C    @08000@,0+X2
               BL   LVFAAA
               C    @12000@,0+X2
               BL   LUFAAA
               S    @12000@,0+X2
               MZ   @A@,3+X2
               B    LWFAAA
     LUFAAA    S    @08000@,0+X2
               MZ   @I@,3+X2
               B    LWFAAA
     LVFAAA    S    @04000@,0+X2
               MZ   @S@,3+X2
     * For some reason the zone bits get set - it still works though.
     LWFAAA    C    @01000@,0+X2
               BL   LZFAAA
               C    @02000@,0+X2
               BL   LYFAAA
               C    @03000@,0+X2
               BL   LXFAAA
               MZ   @A@,1+X2
               B    LZFAAA
     LXFAAA    MZ   @I@,1+X2
               B    LZFAAA
     LYFAAA    MZ   @S@,1+X2
     LZFAAA    LCA  3+X2,15998+X2
               SBR  X2,15998+X2
               B    0+X1
     LGIAAA    SBR  X1
     * Casts a 3-digit address to a 5-digit number
     * Make room on the stack for an int
               MA   @002@,X2
     * make a copy of the top of the stack
               LCA  15998+X2,3+X2
     * Now zero out the top of the stack
               LCA  @00000@,0+X2
     * Now copy back, shifted over 2 digits
               MCW  3+X2,0+X2
     * Now zero out the zone bits on the stack
               MZ   @0@,0+X2
               MZ   @0@,15999+X2
               MZ   @0@,15998+X2
     * check the high-order digit's zone bits
               BWZ  LHIAAA,1+X2,S
               BWZ  LIIAAA,1+X2,K
               BWZ  LJIAAA,1+X2,B
               B    LKIAAA
     LHIAAA    A    @01000@,0+X2
               B    LKIAAA
     LIIAAA    A    @02000@,0+X2
               B    LKIAAA
     LJIAAA    A    @03000@,0+X2
     LKIAAA    BWZ  LLIAAA,3+X2,S
               BWZ  LMIAAA,3+X2,K
               BWZ  LNIAAA,3+X2,B
               B    LOIAAA
     LLIAAA    A    @04000@,0+X2
               B    LOIAAA
     LMIAAA    A    @08000@,0+X2
               B    LOIAAA
     LNIAAA    A    @12000@,0+X2
     LOIAAA    B    0+X1

     LPFAAA    DCW  @I9G@
     LTEAAA    DCW  @2@
     LVIAAA    DCW  @100000@
     LCEAAA    DCW  @69105@
     LKEAAA    DCW  @B@
     LAIAAA    DCW  @G8B@
     LGEAAA    DCW  @F@
     LJFAAA    DCW  @.@
     LFIAAA    DCW  @'2V@
     LYEAAA    DCW  @N@
     LJHAAA    DCW  @00010@
     LWGAAA    DCW  @006@
     LDGAAA    DCW  @I9B@
     LPEAAA    DCW  @6@
     LCGAAA    DCW  @00000@
     LQFAAA    DCW  @00001@
     LOGAAA    DCW  @'3W@
     LSEAAA    DCW  @3@
     LLEAAA    DCW  @A@
     LHEAAA    DCW  @E@
     LUGAAA    DCW  @I8F@
     LOFAAA    DCW  @003@
     LNGAAA    DCW  @00005@
     LVGAAA    DCW  @007@
     LRGAAA    DCW  @00020@
     LCFAAA    DCW  @R@
     LKHAAA    DCW  @I9C@
     LXIAAA    DCW  @00019@
     LOEAAA    DCW  @7@
     LAFAAA    DCW  @I@
     LFFAAA    DCW  @W@
     LDFAAA    DCW  @ @
     LREAAA    DCW  @4@
     LKFAAA    DCW  @0000J@
     LWIAAA    DCW  @00042@
     LIJAAA    DCW  @-@
     LIEAAA    DCW  @D@
     LBGAAA    DCW  @I9I@
     LZHAAA    DCW  @'7Y@
     LZEAAA    DCW  @O@
     LFJAAA    DCW  @'0W@
     LWEAAA    DCW  @%@
     LXHAAA    DCW  @113@
     LGFAAA    DCW  @L@
     LDEAAA    DCW  @201@
     LLFAAA    DCW  @008@
     LVEAAA    DCW  @0@
     LEFAAA    DCW  @H@
     LFEAAA    DCW  @081@
     LNEAAA    DCW  @8@
     LNHAAA    DCW  @I9D@
     LXEAAA    DCW  @S@
     LAGAAA    DCW  @001@
     LQEAAA    DCW  @5@
     LIFAAA    DCW  @P@
     LOHAAA    DCW  @218@
     LUEAAA    DCW  @1@
     LJEAAA    DCW  @C@
     LEJAAA    DCW  @'0V@
     LRFAAA    DCW  @005@
     LRIAAA    DCW  @'2Y@
     LMEAAA    DCW  @9@
     LYHAAA    DCW  @'4/@
     LEEAAA    DCW  @200@
     LHFAAA    DCW  @G@
     LEGAAA    DCW  @014@
     LSFAAA    DCW  @I9E@
     LBFAAA    DCW  @T@
     LUIAAA    DCW  @333@

               END  START
