     ****************************************************************
     ***  pascal2.s
     ***  Generated by Small-C Compiler on 18-Feb-2015 07:57:33
     ****************************************************************

     READ      EQU  001                * Read area
     PUNCH     EQU  101                * Punch area
     PRINT     EQU  201                * Print area
     
               ORG  87
     X1        DSA  0                  * INDEX REGISTER 1
               ORG  92
     X2        DSA  0                  * INDEX REGISTER 2
               ORG  97
     X3        DSA  0                  * INDEX REGISTER 3
     
     * I need a single digit flag - should I replace this with a DA?
     RF        EQU  340
  
     STACK     EQU  400                * BEGINNING/BOTTOM OF STACK (GROWNS UPWARDS)
     DATA      EQU  1500               * BEGINNING OF STATIC/GLOBAL DATA
     CODE      EQU  2500               * BEGINNING OF CODE  
     
     ****************************************************************  
     
               ORG  DATA               
    
     PRCPOS    DCW  000                * char position in print area
     PUCPOS    DCW  000                * char position in punch area
     PUNSIZ    DCW  @080@              * Size of punch area
     PRTSIZ    DCW  @132@              * Size of print area
     EOS       DCW  @'@                * End Of String char
     EOL       DCW  @;@                * End Of Line char

     XXXX1     DCW  @08000@
     XXXX2     DCW  @12000@
     XXXX3     DCW  @04000@
     XXXX4     DCW  @03000@
     XXXX5     DCW  @02000@
     XXXX6     DCW  @01000@
     XXXX7     DCW  @0@
     XXXX8     DCW  @00000@
     XXXX9     DCW  @002@

     ****************************************************************  

     * SET THE START POSITION OF CODE
               ORG  CODE
     START     NOP  

     * SET THE STACK POINTER
               SBR  X2,STACK

               MCW  X2,X3
               LCA  @69105@,2005
               LCA  @201@,2025
               LCA  @200@,2028
               LCA  @081@,2033
               LCA  EOS,2022
               LCA  @F@,2021
               LCA  @E@,2020
               LCA  @D@,2019
               LCA  @C@,2018
               LCA  @B@,2017
               LCA  @A@,2016
               LCA  @9@,2015
               LCA  @8@,2014
               LCA  @7@,2013
               LCA  @6@,2012
               LCA  @5@,2011
               LCA  @4@,2010
               LCA  @3@,2009
               LCA  @2@,2008
               LCA  @1@,2007
               LCA  @0@,2006
               LCA  EOS,2040
               LCA  @C@,2039
               LCA  @%@,2038
               LCA  @D@,2037
               LCA  @%@,2036
               LCA  EOS,2077
               LCA  EOL,2076
               LCA  EOL,2075
               LCA  @S@,2074
               LCA  @N@,2073
               LCA  @O@,2072
               LCA  @I@,2071
               LCA  @T@,2070
               LCA  @A@,2069
               LCA  @R@,2068
               LCA  @E@,2067
               LCA  @T@,2066
               LCA  @I@,2065
               LCA  @ @,2064
               LCA  @D@,2063
               LCA  @%@,2062
               LCA  @ @,2061
               LCA  @H@,2060
               LCA  @T@,2059
               LCA  @I@,2058
               LCA  @W@,2057
               LCA  @ @,2056
               LCA  @E@,2055
               LCA  @L@,2054
               LCA  @G@,2053
               LCA  @N@,2052
               LCA  @A@,2051
               LCA  @I@,2050
               LCA  @R@,2049
               LCA  @T@,2048
               LCA  @ @,2047
               LCA  @L@,2046
               LCA  @A@,2045
               LCA  @C@,2044
               LCA  @S@,2043
               LCA  @A@,2042
               LCA  @P@,2041
               LCA  EOS,2085
               LCA  EOL,2084
               LCA  @.@,2083
               LCA  @E@,2082
               LCA  @N@,2081
               LCA  @O@,2080
               LCA  @D@,2079
               LCA  EOL,2078
               B    LBCAAA
     
               H
     *         B    *-3                * THIS AVOIDS ERRONEOUS CONTINUATIONS BUT IT FREEZES ROPE. TO BE FIXED
         
     * FunctionDefinition((20))
     LUAAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3
     * BlockStatement(LVAAAA:null:3)
               MA   @003@,X2
     * if(retree.statement.BlockStatement@4c17a6bd:retree.statement.BlockStatement@24c3e952)
     * NotEqualExpression(c:'\n')
     * VariableExpression(c:-3:false)
     * Push(15997+X3:1)
               MA   @001@,X2
               LCA  15997+X3,0+X2
     * ConstantExpression(10)
     * Push(EOL:1)
               MA   @001@,X2
               LCA  EOL,0+X2
               C    0+X2,15999+X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               BE   LJCAAA
               B    LKCAAA
     LJCAAA    MCW  @00000@,0+X2
     LKCAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LHCAAA,5+X2, 
     * BlockStatement(LWAAAA:LVAAAA:0)
     * Assignment(( *(__putchar_pos++) )=c)
     * VariableExpression(c:-3:false)
     * Push(15997+X3:1)
               MA   @001@,X2
               LCA  15997+X3,0+X2
     * PostIncrement(__putchar_pos)
     * Push(@!25@:3)
               MA   @003@,X2
               LCA  @!25@,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:3)
               MA   @003@,X2
               LCA  0+X1,0+X2
               MA   @001@,0+X1
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:1)
               LCA  0+X2,0+X1
               MA   @I9I@,X2
     LWAAAA    NOP  
               BCE  LVAAAA,RF,R
               B    LICAAA
     LHCAAA    NOP  
     * BlockStatement(LXAAAA:LVAAAA:0)
     LLCAAA    NOP  
     * GreaterThanOrEqualExpression(((int) __putchar_last):((int) __putchar_pos))
     * VariableExpression(__putchar_last:2028:true)
     * Push(2028:3)
               MA   @003@,X2
               LCA  2028,0+X2
               B    LNCAAA
               B    LWCAAA
     * VariableExpression(__putchar_pos:2025:true)
     * Push(2025:3)
               MA   @003@,X2
               LCA  2025,0+X2
               B    LNCAAA
               B    LWCAAA
               C    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
               MCW  @00001@,0+X2
               BL   LYCAAA
               B    LZCAAA
     LYCAAA    MCW  @00000@,0+X2
     LZCAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LMCAAA,5+X2, 
     * BlockStatement(LYAAAA:LXAAAA:0)
     * Assignment(( *(__putchar_last--) )=' ')
     * ConstantExpression(32)
     * Push(@ @:1)
               MA   @001@,X2
               LCA  @ @,0+X2
     * PostDecrement(__putchar_last)
     * Push(@!28@:3)
               MA   @003@,X2
               LCA  @!28@,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:3)
               MA   @003@,X2
               LCA  0+X1,0+X2
               MA   @I9I@,0+X1
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:1)
               LCA  0+X2,0+X1
               MA   @I9I@,X2
     LYAAAA    NOP  
               BCE  LXAAAA,RF,R
               B    LLCAAA
     LMCAAA    NOP  
     * Assignment(__putchar_last=__putchar_pos)
     * VariableExpression(__putchar_pos:2025:true)
     * Push(2025:3)
               MA   @003@,X2
               LCA  2025,0+X2
     * Push(@!28@:3)
               MA   @003@,X2
               LCA  @!28@,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:3)
               LCA  0+X2,0+X1
               MA   @I9G@,X2
     * Assignment(__putchar_pos=(201))
     * ConstantExpression(201)
     * Push(@201@:3)
               MA   @003@,X2
               LCA  @201@,0+X2
     * Push(@!25@:3)
               MA   @003@,X2
               LCA  @!25@,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:3)
               LCA  0+X2,0+X1
               MA   @I9G@,X2
     * Start asm block
               W    
     * End asm block
     LXAAAA    NOP  
               BCE  LVAAAA,RF,R
     LICAAA    NOP  
     * if(retree.statement.BlockStatement@3a0b1959:null)
     * EqualExpression(__putchar_pos:(333))
     * VariableExpression(__putchar_pos:2025:true)
     * Push(2025:3)
               MA   @003@,X2
               LCA  2025,0+X2
     * ConstantExpression(333)
     * Push(@333@:3)
               MA   @003@,X2
               LCA  @333@,0+X2
               C    0+X2,15997+X2
     * Pop(3)
               MA   @I9G@,X2
     * Pop(3)
               MA   @I9G@,X2
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
               BE   LBDAAA
               B    LCDAAA
     LBDAAA    MCW  @00001@,0+X2
     LCDAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LADAAA,5+X2, 
     * BlockStatement(LZAAAA:LVAAAA:0)
     * Assignment(__putchar_last=__putchar_pos)
     * VariableExpression(__putchar_pos:2025:true)
     * Push(2025:3)
               MA   @003@,X2
               LCA  2025,0+X2
     * Push(@!28@:3)
               MA   @003@,X2
               LCA  @!28@,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:3)
               LCA  0+X2,0+X1
               MA   @I9G@,X2
     * Assignment(__putchar_pos=(201))
     * ConstantExpression(201)
     * Push(@201@:3)
               MA   @003@,X2
               LCA  @201@,0+X2
     * Push(@!25@:3)
               MA   @003@,X2
               LCA  @!25@,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:3)
               LCA  0+X2,0+X1
               MA   @I9G@,X2
     * Start asm block
               W    
     * End asm block
     LZAAAA    NOP  
               BCE  LVAAAA,RF,R
     LADAAA    NOP  
     LVAAAA    NOP  
               MA   @I9G@,X2
               MCW  @ @,RF
               LCA  3+X3,X1
               B    0+X1
     * FunctionDefinition((26))
     LABAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3
     * BlockStatement(LBBAAA:null:3)
               MA   @003@,X2
     LDDAAA    NOP  
     * NotEqualExpression(( *s ):'\0')
     * DereferenceExpression(s)
     * VariableExpression(s:-3:false)
     * Push(15997+X3:3)
               MA   @003@,X2
               LCA  15997+X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:1)
               MA   @001@,X2
               LCA  0+X1,0+X2
     * ConstantExpression(0)
     * Push(EOS:1)
               MA   @001@,X2
               LCA  EOS,0+X2
               C    0+X2,15999+X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               BE   LFDAAA
               B    LGDAAA
     LFDAAA    MCW  @00000@,0+X2
     LGDAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LEDAAA,5+X2, 
     * BlockStatement(LCBAAA:LBBAAA:0)
     * FunctionCallExpr((20))
     * Push(5)
               MA   @005@,X2
     * DereferenceExpression((s++))
     * PostIncrement(s)
     * Push(@I9G@:3)
               MA   @003@,X2
               LCA  @I9G@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:3)
               MA   @003@,X2
               LCA  0+X1,0+X2
               MA   @001@,0+X1
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:1)
               MA   @001@,X2
               LCA  0+X1,0+X2
     * Push(X3:3)
               MA   @003@,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LUAAAA
     * Pop(X3:3)
               LCA  0+X2,X3
               MA   @I9G@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(5)
               MA   @I9E@,X2
     LCBAAA    NOP  
               BCE  LBBAAA,RF,R
               B    LDDAAA
     LEDAAA    NOP  
     LBBAAA    NOP  
               MA   @I9G@,X2
               MCW  @ @,RF
               LCA  3+X3,X1
               B    0+X1
     * FunctionDefinition((7))
     LHAAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3
     * BlockStatement(LIAAAA:null:3)
               MA   @003@,X2
     LHDAAA    NOP  
     * NotEqualExpression((( *(dest++) ) = ( *(src++) )):'\0')
     * Assignment(( *(dest++) )=( *(src++) ))
     * DereferenceExpression((src++))
     * PostIncrement(src)
     * Push(@I9D@:3)
               MA   @003@,X2
               LCA  @I9D@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:3)
               MA   @003@,X2
               LCA  0+X1,0+X2
               MA   @001@,0+X1
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:1)
               MA   @001@,X2
               LCA  0+X1,0+X2
     * PostIncrement(dest)
     * Push(@I9G@:3)
               MA   @003@,X2
               LCA  @I9G@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:3)
               MA   @003@,X2
               LCA  0+X1,0+X2
               MA   @001@,0+X1
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
               LCA  0+X2,0+X1
     * ConstantExpression(0)
     * Push(EOS:1)
               MA   @001@,X2
               LCA  EOS,0+X2
               C    0+X2,15999+X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               BE   LJDAAA
               B    LKDAAA
     LJDAAA    MCW  @00000@,0+X2
     LKDAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LIDAAA,5+X2, 
               B    LHDAAA
     LIDAAA    NOP  
     LIAAAA    NOP  
               MA   @I9G@,X2
               MCW  @ @,RF
               LCA  3+X3,X1
               B    0+X1
     * FunctionDefinition((47))
     LVBAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3
     * BlockStatement(LWBAAA:null:14)
               MA   @014@,X2
     * ForStatement((i = 1),(i < d)'(i++):retree.statement.BlockStatement@70398f3c:LYBAAA:LZBAAA:LACAAA)
     * Assignment(i=1)
     * ConstantExpression(1)
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
     * Push(@008@:3)
               MA   @003@,X2
               LCA  @008@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:5)
               LCA  0+X2,0+X1
               MA   @I9E@,X2
     LYBAAA    NOP  
     * LessThanExpression(i:d)
     * VariableExpression(i:8:false)
     * Push(8+X3:5)
               MA   @005@,X2
               LCA  8+X3,0+X2
               B    LWCAAA
     * VariableExpression(d:-9:false)
     * Push(15991+X3:5)
               MA   @005@,X2
               LCA  15991+X3,0+X2
               B    LWCAAA
               C    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
               MCW  @00000@,0+X2
               BL   LLDAAA
               B    LMDAAA
     LLDAAA    MCW  @00001@,0+X2
     LMDAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LZBAAA,5+X2, 
     * BlockStatement(LXBAAA:LWBAAA:0)
     * Assignment(v=((y[i]) = ((x[(i - 1)]) + (x[i]))))
     * Assignment((y[i])=((x[(i - 1)]) + (x[i])))
     * Addition((x[(i - 1)])+(x[i]))
     * SubScriptEpression(x:(i - 1))
     * VariableExpression(x:-3:false)
     * Push(15997+X3:3)
               MA   @003@,X2
               LCA  15997+X3,0+X2
     * Subtraction(i-1)
     * VariableExpression(i:8:false)
     * Push(8+X3:5)
               MA   @005@,X2
               LCA  8+X3,0+X2
     * ConstantExpression(1)
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               S    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * raw index on the stack
     * Push(@00005@:5)
               MA   @005@,X2
               LCA  @00005@,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * STACK TOP IS NOW ARRAY INDEX
               B    LNDAAA
               MA   0+X2,15997+X2
     * Pop(3)
               MA   @I9G@,X2
     * STACK top is location in array now.
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:5)
               MA   @005@,X2
               LCA  0+X1,0+X2
     * SubScriptEpression(x:i)
     * VariableExpression(x:-3:false)
     * Push(15997+X3:3)
               MA   @003@,X2
               LCA  15997+X3,0+X2
     * VariableExpression(i:8:false)
     * Push(8+X3:5)
               MA   @005@,X2
               LCA  8+X3,0+X2
     * raw index on the stack
     * Push(@00005@:5)
               MA   @005@,X2
               LCA  @00005@,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * STACK TOP IS NOW ARRAY INDEX
               B    LNDAAA
               MA   0+X2,15997+X2
     * Pop(3)
               MA   @I9G@,X2
     * STACK top is location in array now.
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:5)
               MA   @005@,X2
               LCA  0+X1,0+X2
               A    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * VariableExpression(y:-6:false)
     * Push(15994+X3:3)
               MA   @003@,X2
               LCA  15994+X3,0+X2
     * VariableExpression(i:8:false)
     * Push(8+X3:5)
               MA   @005@,X2
               LCA  8+X3,0+X2
     * raw index on the stack
     * Push(@00005@:5)
               MA   @005@,X2
               LCA  @00005@,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * STACK TOP IS NOW ARRAY INDEX
               B    LNDAAA
               MA   0+X2,15997+X2
     * Pop(3)
               MA   @I9G@,X2
     * STACK top is location in array now.
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
               LCA  0+X2,0+X1
     * Push(@013@:3)
               MA   @003@,X2
               LCA  @013@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:5)
               LCA  0+X2,0+X1
               MA   @I9E@,X2
     * Assignment(c=retree.expression.TernaryExpression@3b8e754c)
     * TernaryExpression((i < (d - 1)):' ':'\n')
     * LessThanExpression(i:(d - 1))
     * VariableExpression(i:8:false)
     * Push(8+X3:5)
               MA   @005@,X2
               LCA  8+X3,0+X2
               B    LWCAAA
     * Subtraction(d-1)
     * VariableExpression(d:-9:false)
     * Push(15991+X3:5)
               MA   @005@,X2
               LCA  15991+X3,0+X2
     * ConstantExpression(1)
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               S    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
               B    LWCAAA
               C    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
               MCW  @00000@,0+X2
               BL   LWDAAA
               B    LXDAAA
     LWDAAA    MCW  @00001@,0+X2
     LXDAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LUDAAA,5+X2, 
     * ConstantExpression(32)
     * Push(@ @:1)
               MA   @001@,X2
               LCA  @ @,0+X2
               B    LVDAAA
     LUDAAA    NOP  
     * ConstantExpression(10)
     * Push(EOL:1)
               MA   @001@,X2
               LCA  EOL,0+X2
     LVDAAA    NOP  
     * Push(@014@:3)
               MA   @003@,X2
               LCA  @014@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:1)
               LCA  0+X2,0+X1
               MA   @I9I@,X2
     * FunctionCallExpr((36))
     * Push(5)
               MA   @005@,X2
     * VariableExpression(c:14:false)
     * Push(14+X3:1)
               MA   @001@,X2
               LCA  14+X3,0+X2
     * VariableExpression(v:13:false)
     * Push(13+X3:5)
               MA   @005@,X2
               LCA  13+X3,0+X2
     * ArrayNameExpresssion("%d%c":char [5])
     * Push(@!36@:3)
               MA   @003@,X2
               LCA  @!36@,0+X2
     * Push(X3:3)
               MA   @003@,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LKBAAA
     * Pop(X3:3)
               LCA  0+X2,X3
               MA   @I9G@,X2
     * Pop(3)
               MA   @I9G@,X2
     * Pop(5)
               MA   @I9E@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(5)
               MA   @I9E@,X2
     LXBAAA    NOP  
               BCE  LWBAAA,RF,R
     LACAAA    NOP  
     * PostIncrement(i)
     * Push(@008@:3)
               MA   @003@,X2
               LCA  @008@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
               A    @00001@,0+X1
               B    LYBAAA
     LZBAAA    NOP  
     * TernaryExpression((20 >= d):(47( y x (d + 1))):0)
     * GreaterThanOrEqualExpression(20:d)
     * ConstantExpression(20)
     * Push(@00020@:5)
               MA   @005@,X2
               LCA  @00020@,0+X2
               B    LWCAAA
     * VariableExpression(d:-9:false)
     * Push(15991+X3:5)
               MA   @005@,X2
               LCA  15991+X3,0+X2
               B    LWCAAA
               C    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
               MCW  @00001@,0+X2
               BL   LAEAAA
               B    LBEAAA
     LAEAAA    MCW  @00000@,0+X2
     LBEAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LYDAAA,5+X2, 
     * FunctionCallExpr((47))
     * Push(5)
               MA   @005@,X2
     * Addition(d+1)
     * VariableExpression(d:-9:false)
     * Push(15991+X3:5)
               MA   @005@,X2
               LCA  15991+X3,0+X2
     * ConstantExpression(1)
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               A    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * VariableExpression(x:-3:false)
     * Push(15997+X3:3)
               MA   @003@,X2
               LCA  15997+X3,0+X2
     * VariableExpression(y:-6:false)
     * Push(15994+X3:3)
               MA   @003@,X2
               LCA  15994+X3,0+X2
     * Push(X3:3)
               MA   @003@,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LVBAAA
     * Pop(X3:3)
               LCA  0+X2,X3
               MA   @I9G@,X2
     * Pop(3)
               MA   @I9G@,X2
     * Pop(3)
               MA   @I9G@,X2
     * Pop(5)
               MA   @I9E@,X2
               B    LZDAAA
     LYDAAA    NOP  
     * ConstantExpression(0)
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
     LZDAAA    NOP  
     * Pop(15986+X3:5)
               LCA  0+X2,15986+X3
               MA   @I9E@,X2
     * set the return flag, so we know do deallocate our stack
               MCW  @R@,RF
     * and branch
               B    LWBAAA
     LWBAAA    NOP  
               MA   @I8F@,X2
               MCW  @ @,RF
               LCA  3+X3,X1
               B    0+X1
     * FunctionDefinition((1))
     LBAAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3
     * BlockStatement(LCAAAA:null:3)
               MA   @003@,X2
     * Assignment(seed=retree.expression.ModuloExpression@2d0d20ce)
     * ModuloExpression(((42 * seed) + 19):100000)
     * ConstantExpression(100000)
     * Push(@100000@:5)
               MA   @005@,X2
               LCA  @100000@,0+X2
     * Addition((42 * seed)+19)
     * Multiplication(42*seed)
     * ConstantExpression(42)
     * Push(@00042@:5)
               MA   @005@,X2
               LCA  @00042@,0+X2
     * VariableExpression(seed:2005:true)
     * Push(2005:5)
               MA   @005@,X2
               LCA  2005,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * ConstantExpression(19)
     * Push(@00019@:5)
               MA   @005@,X2
               LCA  @00019@,0+X2
               A    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
               B    LCEAAA
     * Pop(5)
               MA   @I9E@,X2
     * Push(@!05@:3)
               MA   @003@,X2
               LCA  @!05@,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:5)
               LCA  0+X2,0+X1
               MA   @I9E@,X2
     * VariableExpression(seed:2005:true)
     * Push(2005:5)
               MA   @005@,X2
               LCA  2005,0+X2
     * Pop(15997+X3:5)
               LCA  0+X2,15997+X3
               MA   @I9E@,X2
     * set the return flag, so we know do deallocate our stack
               MCW  @R@,RF
     * and branch
               B    LCAAAA
     LCAAAA    NOP  
               MA   @I9G@,X2
               MCW  @ @,RF
               LCA  3+X3,X1
               B    0+X1
     * FunctionDefinition((15))
     LPAAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3
     * BlockStatement(LQAAAA:null:14)
               LCA  @!06@,9+X3
               LCA  @00001@,14+X3
               MA   @014@,X2
     * Assignment(start=str)
     * VariableExpression(str:-8:false)
     * Push(15992+X3:3)
               MA   @003@,X2
               LCA  15992+X3,0+X2
     * Push(@006@:3)
               MA   @003@,X2
               LCA  @006@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:3)
               LCA  0+X2,0+X1
               MA   @I9G@,X2
     * if(retree.statement.BlockStatement@34eb98b9:retree.statement.IfStatement@5777b4d3)
     * LessThanExpression(value:0)
     * VariableExpression(value:-3:false)
     * Push(15997+X3:5)
               MA   @005@,X2
               LCA  15997+X3,0+X2
               B    LWCAAA
     * ConstantExpression(0)
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
               B    LWCAAA
               C    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
               MCW  @00000@,0+X2
               BL   LKEAAA
               B    LLEAAA
     LKEAAA    MCW  @00001@,0+X2
     LLEAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LIEAAA,5+X2, 
     * BlockStatement(LRAAAA:LQAAAA:0)
     * Assignment(( *(str++) )='-')
     * ConstantExpression(45)
     * Push(@-@:1)
               MA   @001@,X2
               LCA  @-@,0+X2
     * PostIncrement(str)
     * Push(@I9B@:3)
               MA   @003@,X2
               LCA  @I9B@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:3)
               MA   @003@,X2
               LCA  0+X1,0+X2
               MA   @001@,0+X1
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:1)
               LCA  0+X2,0+X1
               MA   @I9I@,X2
     * Assignment(value=(-value))
     * NegExpression(value)
     * VariableExpression(value:-3:false)
     * Push(15997+X3:5)
               MA   @005@,X2
               LCA  15997+X3,0+X2
               ZS   0+X2
               B    LWCAAA
     * Push(@I9G@:3)
               MA   @003@,X2
               LCA  @I9G@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:5)
               LCA  0+X2,0+X1
               MA   @I9E@,X2
     LRAAAA    NOP  
               BCE  LQAAAA,RF,R
               B    LJEAAA
     LIEAAA    NOP  
     * if(retree.statement.BlockStatement@7400b581:null)
     * EqualExpression(value:0)
     * VariableExpression(value:-3:false)
     * Push(15997+X3:5)
               MA   @005@,X2
               LCA  15997+X3,0+X2
               B    LWCAAA
     * ConstantExpression(0)
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
               B    LWCAAA
               C    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * Pop(5)
               MA   @I9E@,X2
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
               BE   LNEAAA
               B    LOEAAA
     LNEAAA    MCW  @00001@,0+X2
     LOEAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LMEAAA,5+X2, 
     * BlockStatement(LSAAAA:LQAAAA:0)
     * Assignment((str[0])='0')
     * ConstantExpression(48)
     * Push(@0@:1)
               MA   @001@,X2
               LCA  @0@,0+X2
     * VariableExpression(str:-8:false)
     * Push(15992+X3:3)
               MA   @003@,X2
               LCA  15992+X3,0+X2
     * ConstantExpression(0)
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
     * raw index on the stack
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * STACK TOP IS NOW ARRAY INDEX
               B    LNDAAA
               MA   0+X2,15997+X2
     * Pop(3)
               MA   @I9G@,X2
     * STACK top is location in array now.
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:1)
               LCA  0+X2,0+X1
               MA   @I9I@,X2
     * Assignment((str[1])='\0')
     * ConstantExpression(0)
     * Push(EOS:1)
               MA   @001@,X2
               LCA  EOS,0+X2
     * VariableExpression(str:-8:false)
     * Push(15992+X3:3)
               MA   @003@,X2
               LCA  15992+X3,0+X2
     * ConstantExpression(1)
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
     * raw index on the stack
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * STACK TOP IS NOW ARRAY INDEX
               B    LNDAAA
               MA   0+X2,15997+X2
     * Pop(3)
               MA   @I9G@,X2
     * STACK top is location in array now.
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:1)
               LCA  0+X2,0+X1
               MA   @I9I@,X2
     * VariableExpression(start:6:false)
     * Push(6+X3:3)
               MA   @003@,X2
               LCA  6+X3,0+X2
     * Pop(15984+X3:3)
               LCA  0+X2,15984+X3
               MA   @I9G@,X2
     * set the return flag, so we know do deallocate our stack
               MCW  @R@,RF
     * and branch
               B    LSAAAA
     LSAAAA    NOP  
               BCE  LQAAAA,RF,R
     LMEAAA    NOP  
     LJEAAA    NOP  
     LPEAAA    NOP  
     * LessThanOrEqualExpression(exp:retree.expression.DivideExpression@36e255bb)
     * VariableExpression(exp:14:false)
     * Push(14+X3:5)
               MA   @005@,X2
               LCA  14+X3,0+X2
               B    LWCAAA
     * Divide(value/base)
     * VariableExpression(base:-11:false)
     * Push(15989+X3:5)
               MA   @005@,X2
               LCA  15989+X3,0+X2
     * VariableExpression(value:-3:false)
     * Push(15997+X3:5)
               MA   @005@,X2
               LCA  15997+X3,0+X2
               B    LCEAAA
               MCW  0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
               B    LWCAAA
               C    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
               MCW  @00001@,0+X2
               BH   LREAAA
               B    LSEAAA
     LREAAA    MCW  @00000@,0+X2
     LSEAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LQEAAA,5+X2, 
     * Assignment(exp=(exp * base))
     * Multiplication(exp*base)
     * VariableExpression(exp:14:false)
     * Push(14+X3:5)
               MA   @005@,X2
               LCA  14+X3,0+X2
     * VariableExpression(base:-11:false)
     * Push(15989+X3:5)
               MA   @005@,X2
               LCA  15989+X3,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * Push(@014@:3)
               MA   @003@,X2
               LCA  @014@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:5)
               LCA  0+X2,0+X1
               MA   @I9E@,X2
               B    LPEAAA
     LQEAAA    NOP  
     LTEAAA    NOP  
     * VariableExpression(exp:14:false)
     * Push(14+X3:5)
               MA   @005@,X2
               LCA  14+X3,0+X2
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LUEAAA,5+X2, 
     * BlockStatement(LTAAAA:LQAAAA:0)
     * Assignment(( *(str++) )=(digits[retree.expression.DivideExpression@456a8423]))
     * SubScriptEpression(digits:retree.expression.DivideExpression@456a8423)
     * VariableExpression(digits:9:false)
     * Push(9+X3:3)
               MA   @003@,X2
               LCA  9+X3,0+X2
     * Divide(value/exp)
     * VariableExpression(exp:14:false)
     * Push(14+X3:5)
               MA   @005@,X2
               LCA  14+X3,0+X2
     * VariableExpression(value:-3:false)
     * Push(15997+X3:5)
               MA   @005@,X2
               LCA  15997+X3,0+X2
               B    LCEAAA
               MCW  0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * raw index on the stack
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * STACK TOP IS NOW ARRAY INDEX
               B    LNDAAA
               MA   0+X2,15997+X2
     * Pop(3)
               MA   @I9G@,X2
     * STACK top is location in array now.
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:1)
               MA   @001@,X2
               LCA  0+X1,0+X2
     * PostIncrement(str)
     * Push(@I9B@:3)
               MA   @003@,X2
               LCA  @I9B@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:3)
               MA   @003@,X2
               LCA  0+X1,0+X2
               MA   @001@,0+X1
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:1)
               LCA  0+X2,0+X1
               MA   @I9I@,X2
     * Assignment(value=retree.expression.ModuloExpression@5409396f)
     * ModuloExpression(value:exp)
     * VariableExpression(exp:14:false)
     * Push(14+X3:5)
               MA   @005@,X2
               LCA  14+X3,0+X2
     * VariableExpression(value:-3:false)
     * Push(15997+X3:5)
               MA   @005@,X2
               LCA  15997+X3,0+X2
               B    LCEAAA
     * Pop(5)
               MA   @I9E@,X2
     * Push(@I9G@:3)
               MA   @003@,X2
               LCA  @I9G@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:5)
               LCA  0+X2,0+X1
               MA   @I9E@,X2
     * Assignment(exp=retree.expression.DivideExpression@5c40c4d5)
     * Divide(exp/base)
     * VariableExpression(base:-11:false)
     * Push(15989+X3:5)
               MA   @005@,X2
               LCA  15989+X3,0+X2
     * VariableExpression(exp:14:false)
     * Push(14+X3:5)
               MA   @005@,X2
               LCA  14+X3,0+X2
               B    LCEAAA
               MCW  0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * Push(@014@:3)
               MA   @003@,X2
               LCA  @014@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:5)
               LCA  0+X2,0+X1
               MA   @I9E@,X2
     LTAAAA    NOP  
               BCE  LQAAAA,RF,R
               B    LTEAAA
     LUEAAA    NOP  
     * Assignment(( *str )='\0')
     * ConstantExpression(0)
     * Push(EOS:1)
               MA   @001@,X2
               LCA  EOS,0+X2
     * VariableExpression(str:-8:false)
     * Push(15992+X3:3)
               MA   @003@,X2
               LCA  15992+X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:1)
               LCA  0+X2,0+X1
               MA   @I9I@,X2
     * VariableExpression(start:6:false)
     * Push(6+X3:3)
               MA   @003@,X2
               LCA  6+X3,0+X2
     * Pop(15984+X3:3)
               LCA  0+X2,15984+X3
               MA   @I9G@,X2
     * set the return flag, so we know do deallocate our stack
               MCW  @R@,RF
     * and branch
               B    LQAAAA
     LQAAAA    NOP  
               MA   @I8F@,X2
               MCW  @ @,RF
               LCA  3+X3,X1
               B    0+X1
     * FunctionDefinition((36))
     LKBAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3
     * BlockStatement(LLBAAA:null:7)
               MA   @007@,X2
     * Assignment(arg=((*char) (( &cformat_str ) + (15997))))
     * Addition(( &cformat_str )+(15997))
     * AddressOfExpression(cformat_str)
     * Push(@I9G@:3)
               MA   @003@,X2
               LCA  @I9G@,0+X2
               MA   X3,0+X2
     * ConstantExpression(15997)
     * Push(@I9G@:3)
               MA   @003@,X2
               LCA  @I9G@,0+X2
               MA   0+X2,15997+X2
     * Pop(3)
               MA   @I9G@,X2
     * Push(@006@:3)
               MA   @003@,X2
               LCA  @006@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:3)
               LCA  0+X2,0+X1
               MA   @I9G@,X2
     LVEAAA    NOP  
     * NotEqualExpression((c = ( *(cformat_str++) )):'\0')
     * Assignment(c=( *(cformat_str++) ))
     * DereferenceExpression((cformat_str++))
     * PostIncrement(cformat_str)
     * Push(@I9G@:3)
               MA   @003@,X2
               LCA  @I9G@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:3)
               MA   @003@,X2
               LCA  0+X1,0+X2
               MA   @001@,0+X1
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:1)
               MA   @001@,X2
               LCA  0+X1,0+X2
     * Push(@007@:3)
               MA   @003@,X2
               LCA  @007@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
               LCA  0+X2,0+X1
     * ConstantExpression(0)
     * Push(EOS:1)
               MA   @001@,X2
               LCA  EOS,0+X2
               C    0+X2,15999+X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               BE   LXEAAA
               B    LYEAAA
     LXEAAA    MCW  @00000@,0+X2
     LYEAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LWEAAA,5+X2, 
     * BlockStatement(LMBAAA:LLBAAA:0)
     * if(retree.statement.ExpressionStatement@111de95a:retree.statement.BlockStatement@42c31c7d)
     * NotEqualExpression(c:'%')
     * VariableExpression(c:7:false)
     * Push(7+X3:1)
               MA   @001@,X2
               LCA  7+X3,0+X2
     * ConstantExpression(37)
     * Push(@%@:1)
               MA   @001@,X2
               LCA  @%@,0+X2
               C    0+X2,15999+X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               BE   LBFAAA
               B    LCFAAA
     LBFAAA    MCW  @00000@,0+X2
     LCFAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LZEAAA,5+X2, 
     * FunctionCallExpr((20))
     * Push(5)
               MA   @005@,X2
     * VariableExpression(c:7:false)
     * Push(7+X3:1)
               MA   @001@,X2
               LCA  7+X3,0+X2
     * Push(X3:3)
               MA   @003@,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LUAAAA
     * Pop(X3:3)
               LCA  0+X2,X3
               MA   @I9G@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(5)
               MA   @I9E@,X2
               B    LAFAAA
     LZEAAA    NOP  
     * BlockStatement(LNBAAA:LMBAAA:0)
     * Assignment(c=( *(cformat_str++) ))
     * DereferenceExpression((cformat_str++))
     * PostIncrement(cformat_str)
     * Push(@I9G@:3)
               MA   @003@,X2
               LCA  @I9G@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:3)
               MA   @003@,X2
               LCA  0+X1,0+X2
               MA   @001@,0+X1
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:1)
               MA   @001@,X2
               LCA  0+X1,0+X2
     * Push(@007@:3)
               MA   @003@,X2
               LCA  @007@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:1)
               LCA  0+X2,0+X1
               MA   @I9I@,X2
     * if(retree.statement.BlockStatement@178374c9:retree.statement.IfStatement@3768442e)
     * EqualExpression(c:'%')
     * VariableExpression(c:7:false)
     * Push(7+X3:1)
               MA   @001@,X2
               LCA  7+X3,0+X2
     * ConstantExpression(37)
     * Push(@%@:1)
               MA   @001@,X2
               LCA  @%@,0+X2
               C    0+X2,15999+X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
               BE   LFFAAA
               B    LGFAAA
     LFFAAA    MCW  @00001@,0+X2
     LGFAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LDFAAA,5+X2, 
     * BlockStatement(LOBAAA:LNBAAA:0)
     * FunctionCallExpr((20))
     * Push(5)
               MA   @005@,X2
     * ConstantExpression(37)
     * Push(@%@:1)
               MA   @001@,X2
               LCA  @%@,0+X2
     * Push(X3:3)
               MA   @003@,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LUAAAA
     * Pop(X3:3)
               LCA  0+X2,X3
               MA   @I9G@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(5)
               MA   @I9E@,X2
     LOBAAA    NOP  
               BCE  LNBAAA,RF,R
               B    LEFAAA
     LDFAAA    NOP  
     * if(retree.statement.BlockStatement@1e54446d:retree.statement.IfStatement@2e585fa9)
     * EqualExpression(c:'C')
     * VariableExpression(c:7:false)
     * Push(7+X3:1)
               MA   @001@,X2
               LCA  7+X3,0+X2
     * ConstantExpression(67)
     * Push(@C@:1)
               MA   @001@,X2
               LCA  @C@,0+X2
               C    0+X2,15999+X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
               BE   LJFAAA
               B    LKFAAA
     LJFAAA    MCW  @00001@,0+X2
     LKFAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LHFAAA,5+X2, 
     * BlockStatement(LPBAAA:LNBAAA:0)
     * FunctionCallExpr((20))
     * Push(5)
               MA   @005@,X2
     * DereferenceExpression((arg--))
     * PostDecrement(arg)
     * Push(@006@:3)
               MA   @003@,X2
               LCA  @006@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:3)
               MA   @003@,X2
               LCA  0+X1,0+X2
               MA   @I9I@,0+X1
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:1)
               MA   @001@,X2
               LCA  0+X1,0+X2
     * Push(X3:3)
               MA   @003@,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LUAAAA
     * Pop(X3:3)
               LCA  0+X2,X3
               MA   @I9G@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(5)
               MA   @I9E@,X2
     LPBAAA    NOP  
               BCE  LNBAAA,RF,R
               B    LIFAAA
     LHFAAA    NOP  
     * if(retree.statement.BlockStatement@2bf06804:retree.statement.IfStatement@343cf525)
     * EqualExpression(c:'S')
     * VariableExpression(c:7:false)
     * Push(7+X3:1)
               MA   @001@,X2
               LCA  7+X3,0+X2
     * ConstantExpression(83)
     * Push(@S@:1)
               MA   @001@,X2
               LCA  @S@,0+X2
               C    0+X2,15999+X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
               BE   LNFAAA
               B    LOFAAA
     LNFAAA    MCW  @00001@,0+X2
     LOFAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LLFAAA,5+X2, 
     * BlockStatement(LQBAAA:LNBAAA:0)
     * FunctionCallExpr((26))
     * Push(5)
               MA   @005@,X2
     * DereferenceExpression(((**char) arg))
     * VariableExpression(arg:6:false)
     * Push(6+X3:3)
               MA   @003@,X2
               LCA  6+X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:3)
               MA   @003@,X2
               LCA  0+X1,0+X2
     * Push(X3:3)
               MA   @003@,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LABAAA
     * Pop(X3:3)
               LCA  0+X2,X3
               MA   @I9G@,X2
     * Pop(3)
               MA   @I9G@,X2
     * Pop(5)
               MA   @I9E@,X2
     * Assignment(arg=(arg + (15997)))
     * Addition(arg+(15997))
     * VariableExpression(arg:6:false)
     * Push(6+X3:3)
               MA   @003@,X2
               LCA  6+X3,0+X2
     * ConstantExpression(15997)
     * Push(@I9G@:3)
               MA   @003@,X2
               LCA  @I9G@,0+X2
               MA   0+X2,15997+X2
     * Pop(3)
               MA   @I9G@,X2
     * Push(@006@:3)
               MA   @003@,X2
               LCA  @006@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:3)
               LCA  0+X2,0+X1
               MA   @I9G@,X2
     LQBAAA    NOP  
               BCE  LNBAAA,RF,R
               B    LMFAAA
     LLFAAA    NOP  
     * if(retree.statement.BlockStatement@e026aee:retree.statement.ReturnStatement@40ba3671)
     * EqualExpression(c:'D')
     * VariableExpression(c:7:false)
     * Push(7+X3:1)
               MA   @001@,X2
               LCA  7+X3,0+X2
     * ConstantExpression(68)
     * Push(@D@:1)
               MA   @001@,X2
               LCA  @D@,0+X2
               C    0+X2,15999+X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
               BE   LRFAAA
               B    LSFAAA
     LRFAAA    MCW  @00001@,0+X2
     LSFAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LPFAAA,5+X2, 
     * BlockStatement(LRBAAA:LNBAAA:7)
               MA   @007@,X2
     * FunctionCallExpr((15))
     * Push(3)
               MA   @003@,X2
     * ConstantExpression(10)
     * Push(@00010@:5)
               MA   @005@,X2
               LCA  @00010@,0+X2
     * ArrayNameExpresssion(a:char [7])
     * Push(@008@:3)
               MA   @003@,X2
               LCA  @008@,0+X2
               MA   X3,0+X2
     * DereferenceExpression(((*int) arg))
     * VariableExpression(arg:6:false)
     * Push(6+X3:3)
               MA   @003@,X2
               LCA  6+X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:5)
               MA   @005@,X2
               LCA  0+X1,0+X2
     * Push(X3:3)
               MA   @003@,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LPAAAA
     * Pop(X3:3)
               LCA  0+X2,X3
               MA   @I9G@,X2
     * Pop(5)
               MA   @I9E@,X2
     * Pop(3)
               MA   @I9G@,X2
     * Pop(5)
               MA   @I9E@,X2
     * Pop(3)
               MA   @I9G@,X2
     * FunctionCallExpr((26))
     * Push(5)
               MA   @005@,X2
     * ArrayNameExpresssion(a:char [7])
     * Push(@008@:3)
               MA   @003@,X2
               LCA  @008@,0+X2
               MA   X3,0+X2
     * Push(X3:3)
               MA   @003@,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LABAAA
     * Pop(X3:3)
               LCA  0+X2,X3
               MA   @I9G@,X2
     * Pop(3)
               MA   @I9G@,X2
     * Pop(5)
               MA   @I9E@,X2
     * Assignment(arg=(arg + (15995)))
     * Addition(arg+(15995))
     * VariableExpression(arg:6:false)
     * Push(6+X3:3)
               MA   @003@,X2
               LCA  6+X3,0+X2
     * ConstantExpression(15995)
     * Push(@I9E@:3)
               MA   @003@,X2
               LCA  @I9E@,0+X2
               MA   0+X2,15997+X2
     * Pop(3)
               MA   @I9G@,X2
     * Push(@006@:3)
               MA   @003@,X2
               LCA  @006@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:3)
               LCA  0+X2,0+X1
               MA   @I9G@,X2
     LRBAAA    NOP  
               MA   @I9C@,X2
               BCE  LNBAAA,RF,R
               B    LQFAAA
     LPFAAA    NOP  
     * set the return flag, so we know do deallocate our stack
               MCW  @R@,RF
     * and branch
               B    LNBAAA
     LQFAAA    NOP  
     LMFAAA    NOP  
     LIFAAA    NOP  
     LEFAAA    NOP  
     LNBAAA    NOP  
               BCE  LMBAAA,RF,R
     LAFAAA    NOP  
     LMBAAA    NOP  
               BCE  LLBAAA,RF,R
               B    LVEAAA
     LWEAAA    NOP  
     LLBAAA    NOP  
               MA   @I9C@,X2
               MCW  @ @,RF
               LCA  3+X3,X1
               B    0+X1
     * FunctionDefinition((53))
     LBCAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3
     * BlockStatement(LCCAAA:null:218)
               MA   @218@,X2
     * ForStatement((i = 0),(i <= 20)'(i++):retree.statement.BlockStatement@761b9c3f:LECAAA:LFCAAA:LGCAAA)
     * Assignment(i=0)
     * ConstantExpression(0)
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
     * Push(@218@:3)
               MA   @003@,X2
               LCA  @218@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:5)
               LCA  0+X2,0+X1
               MA   @I9E@,X2
     LECAAA    NOP  
     * LessThanOrEqualExpression(i:20)
     * VariableExpression(i:218:false)
     * Push(218+X3:5)
               MA   @005@,X2
               LCA  218+X3,0+X2
               B    LWCAAA
     * ConstantExpression(20)
     * Push(@00020@:5)
               MA   @005@,X2
               LCA  @00020@,0+X2
               B    LWCAAA
               C    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
               MCW  @00001@,0+X2
               BH   LTFAAA
               B    LUFAAA
     LTFAAA    MCW  @00000@,0+X2
     LUFAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LFCAAA,5+X2, 
     * BlockStatement(LDCAAA:LCCAAA:0)
     * Assignment((x[i])=retree.expression.TernaryExpression@eaf28ad)
     * TernaryExpression((i == 1):1:0)
     * EqualExpression(i:1)
     * VariableExpression(i:218:false)
     * Push(218+X3:5)
               MA   @005@,X2
               LCA  218+X3,0+X2
               B    LWCAAA
     * ConstantExpression(1)
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               B    LWCAAA
               C    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * Pop(5)
               MA   @I9E@,X2
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
               BE   LXFAAA
               B    LYFAAA
     LXFAAA    MCW  @00001@,0+X2
     LYFAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LVFAAA,5+X2, 
     * ConstantExpression(1)
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               B    LWFAAA
     LVFAAA    NOP  
     * ConstantExpression(0)
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
     LWFAAA    NOP  
     * ArrayNameExpresssion(x:int [21])
     * Push(@008@:3)
               MA   @003@,X2
               LCA  @008@,0+X2
               MA   X3,0+X2
     * VariableExpression(i:218:false)
     * Push(218+X3:5)
               MA   @005@,X2
               LCA  218+X3,0+X2
     * raw index on the stack
     * Push(@00005@:5)
               MA   @005@,X2
               LCA  @00005@,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * STACK TOP IS NOW ARRAY INDEX
               B    LNDAAA
               MA   0+X2,15997+X2
     * Pop(3)
               MA   @I9G@,X2
     * STACK top is location in array now.
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:5)
               LCA  0+X2,0+X1
               MA   @I9E@,X2
     * Assignment((y[i])=0)
     * ConstantExpression(0)
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
     * ArrayNameExpresssion(y:int [21])
     * Push(@113@:3)
               MA   @003@,X2
               LCA  @113@,0+X2
               MA   X3,0+X2
     * VariableExpression(i:218:false)
     * Push(218+X3:5)
               MA   @005@,X2
               LCA  218+X3,0+X2
     * raw index on the stack
     * Push(@00005@:5)
               MA   @005@,X2
               LCA  @00005@,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * STACK TOP IS NOW ARRAY INDEX
               B    LNDAAA
               MA   0+X2,15997+X2
     * Pop(3)
               MA   @I9G@,X2
     * STACK top is location in array now.
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:5)
               LCA  0+X2,0+X1
               MA   @I9E@,X2
     LDCAAA    NOP  
               BCE  LCCAAA,RF,R
     LGCAAA    NOP  
     * PostIncrement(i)
     * Push(@218@:3)
               MA   @003@,X2
               LCA  @218@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
               A    @00001@,0+X1
               B    LECAAA
     LFCAAA    NOP  
     * FunctionCallExpr((36))
     * Push(5)
               MA   @005@,X2
     * ConstantExpression(20)
     * Push(@00020@:5)
               MA   @005@,X2
               LCA  @00020@,0+X2
     * ArrayNameExpresssion("Pascal Triangle with %d iterations\n\n":char [37])
     * Push(@!41@:3)
               MA   @003@,X2
               LCA  @!41@,0+X2
     * Push(X3:3)
               MA   @003@,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LKBAAA
     * Pop(X3:3)
               LCA  0+X2,X3
               MA   @I9G@,X2
     * Pop(3)
               MA   @I9G@,X2
     * Pop(5)
               MA   @I9E@,X2
     * Pop(5)
               MA   @I9E@,X2
     * FunctionCallExpr((47))
     * Push(5)
               MA   @005@,X2
     * ConstantExpression(0)
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
     * ArrayNameExpresssion(y:int [21])
     * Push(@113@:3)
               MA   @003@,X2
               LCA  @113@,0+X2
               MA   X3,0+X2
     * ArrayNameExpresssion(x:int [21])
     * Push(@008@:3)
               MA   @003@,X2
               LCA  @008@,0+X2
               MA   X3,0+X2
     * Push(X3:3)
               MA   @003@,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LVBAAA
     * Pop(X3:3)
               LCA  0+X2,X3
               MA   @I9G@,X2
     * Pop(3)
               MA   @I9G@,X2
     * Pop(3)
               MA   @I9G@,X2
     * Pop(5)
               MA   @I9E@,X2
     * Pop(5)
               MA   @I9E@,X2
     * FunctionCallExpr((36))
     * Push(5)
               MA   @005@,X2
     * ArrayNameExpresssion("\nDone.\n":char [8])
     * Push(@!78@:3)
               MA   @003@,X2
               LCA  @!78@,0+X2
     * Push(X3:3)
               MA   @003@,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LKBAAA
     * Pop(X3:3)
               LCA  0+X2,X3
               MA   @I9G@,X2
     * Pop(3)
               MA   @I9G@,X2
     * Pop(5)
               MA   @I9E@,X2
     LCCAAA    NOP  
               MA   @G8B@,X2
               MCW  @ @,RF
               LCA  3+X3,X1
               B    0+X1
     * FunctionDefinition((5))
     LFAAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3
     * BlockStatement(LGAAAA:null:8)
               LCA  @0000J@,8+X3
               MA   @008@,X2
     LZFAAA    NOP  
     * NotEqualExpression((str[(++len)]):'\0')
     * SubScriptEpression(str:(++len))
     * VariableExpression(str:-3:false)
     * Push(15997+X3:3)
               MA   @003@,X2
               LCA  15997+X3,0+X2
     * PreIncrement(len)
     * Push(@008@:3)
               MA   @003@,X2
               LCA  @008@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
               A    @00001@,0+X1
     * Push(0+X1:5)
               MA   @005@,X2
               LCA  0+X1,0+X2
     * raw index on the stack
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * STACK TOP IS NOW ARRAY INDEX
               B    LNDAAA
               MA   0+X2,15997+X2
     * Pop(3)
               MA   @I9G@,X2
     * STACK top is location in array now.
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:1)
               MA   @001@,X2
               LCA  0+X1,0+X2
     * ConstantExpression(0)
     * Push(EOS:1)
               MA   @001@,X2
               LCA  EOS,0+X2
               C    0+X2,15999+X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               BE   LBGAAA
               B    LCGAAA
     LBGAAA    MCW  @00000@,0+X2
     LCGAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LAGAAA,5+X2, 
               B    LZFAAA
     LAGAAA    NOP  
     * VariableExpression(len:8:false)
     * Push(8+X3:5)
               MA   @005@,X2
               LCA  8+X3,0+X2
     * Pop(15994+X3:5)
               LCA  0+X2,15994+X3
               MA   @I9E@,X2
     * set the return flag, so we know do deallocate our stack
               MCW  @R@,RF
     * and branch
               B    LGAAAA
     LGAAAA    NOP  
               MA   @I9B@,X2
               MCW  @ @,RF
               LCA  3+X3,X1
               B    0+X1
     LWCAAA    SBR  X1
     * Normalizes the zone bits of a number, leaving either A=0B=0
     * for a positive or A=0B=1 for a negative
     * Do nothing on either no zone bits or only a b zone bit
               BWZ  LXCAAA,0+X2,2
               BWZ  LXCAAA,0+X2,K
     * else clear the zone bits, as it is positive
               MZ   @ @,0+X2
     LXCAAA    B    0+X1
    ****************************************************************  
    ** DIVISION SNIPPET                                           **
    ****************************************************************  
     
     LCEAAA    SBR  LDEAAA+3           * SETUP RETURN ADDRESS
     * POP DIVIDEND
               MCW  0+X2, LEEAAA
               SBR  X2, 15995+X2

     * POP DIVISOR
               MCW  0+X2, LFEAAA
               SBR  X2, 15995+X2


               B    *+17
               
               DCW  @00000@                
               DC   @00000000000@        

               ZA   LEEAAA, *-7         * PUT DIVIDEND INTO WORKING BL
               D    LFEAAA, *-19        * DIVIDE
               MZ   *-22, *-21          * KILL THE ZONE BIT
               MZ   *-29, *-34          * KILL THE ZONE BIT
               MCW  *-41, LGEAAA        * PICK UP ANSWER
               SW   *-44                * SO I CAN PICKUP REMAINDER
               MCW  *-46, LHEAAA        * GET REMAINDER
               CW   *-55                * CLEAR THE WM
               MZ   LGEAAA-1, LGEAAA    * CLEANUP QUOTIENT BITZONE
               MZ   LHEAAA-1, LHEAAA    * CLEANUP REMAINDER BITZONE
               
     * PUSH REMAINDER
               SBR  X2, 5+X2
               SW   15996+X2
               MCW  LHEAAA, 0+X2
               
     * PUSH QUOTIENT
               SBR  X2, 5+X2
               SW   15996+X2
               MCW  LGEAAA, 0+X2

     LDEAAA    B    000                 * JUMP BACK
               
     LFEAAA    DCW  00000               * DIVISOR
     LEEAAA    DCW  00000               * DIVIDEND
     LGEAAA    DCW  00000               * QUOTIENT
     LHEAAA    DCW  00000               * REMAINDER
     LNDAAA    SBR  X1
     * Casts a 5-digit number to a 3-digit address
     * make a copy of the top of the stack
               SW   15998+X2
               LCA  0+X2,3+X2
               CW   15998+X2
     * zero out the zone bits of our copy
               MZ   @0@,3+X2
               MZ   @0@,2+X2
               MZ   @0@,1+X2
     * set the low-order digit's zone bits
               C    @04000@,0+X2
               BL   LQDAAA
               C    @08000@,0+X2
               BL   LPDAAA
               C    @12000@,0+X2
               BL   LODAAA
               S    @12000@,0+X2
               MZ   @A@,3+X2
               B    LQDAAA
     LODAAA    S    @08000@,0+X2
               MZ   @I@,3+X2
               B    LQDAAA
     LPDAAA    S    @04000@,0+X2
               MZ   @S@,3+X2
     * For some reason the zone bits get set - it still works though.
     LQDAAA    C    @01000@,0+X2
               BL   LTDAAA
               C    @02000@,0+X2
               BL   LSDAAA
               C    @03000@,0+X2
               BL   LRDAAA
               MZ   @A@,1+X2
               B    LTDAAA
     LRDAAA    MZ   @I@,1+X2
               B    LTDAAA
     LSDAAA    MZ   @S@,1+X2
     LTDAAA    LCA  3+X2,15998+X2
               SBR  X2,15998+X2
               B    0+X1
     LNCAAA    SBR  X1
     * Casts a 3-digit address to a 5-digit number
     * Make room on the stack for an int
               MA   XXXX9,X2
     * make a copy of the top of the stack
               LCA  15998+X2,3+X2
     * Now zero out the top of the stack
               LCA  XXXX8,0+X2
     * Now copy back, shifted over 2 digits
               LCA  3+X2,0+X2
     * Now zero out the zone bits on the stack
               MZ   XXXX7,0+X2
               MZ   XXXX7,15999+X2
               MZ   XXXX7,15998+X2
     * check the high-order digit's zone bits
               BWZ  LOCAAA,1+X2,S
               BWZ  LPCAAA,1+X2,K
               BWZ  LQCAAA,1+X2,B
               B    LRCAAA
     LOCAAA    A    XXXX6,0+X2
               B    LRCAAA
     LPCAAA    A    XXXX5,0+X2
               B    LRCAAA
     LQCAAA    A    XXXX4,0+X2
     LRCAAA    BWZ  LSCAAA,3+X2,S
               BWZ  LTCAAA,3+X2,K
               BWZ  LUCAAA,3+X2,B
               B    LVCAAA
     LSCAAA    A    XXXX3,0+X2
               B    LVCAAA
     LTCAAA    A    XXXX1,0+X2
               B    LVCAAA
     LUCAAA    A    XXXX2,0+X2
     LVCAAA    B    0+X1  
     
               END  START
