     ****************************************************************
     ***  pascal.s
     ***  Generated by Small-C Compiler on 18-Feb-2015 19:25:28
     ****************************************************************

     READ      EQU  001                * Read area
     PUNCH     EQU  101                * Punch area
     PRINT     EQU  201                * Print area
     
     PRCPOS    DCW  000                * char position in print area
     PUCPOS    DCW  000                * char position in punch area
     PUNSIZ    DCW  @080@              * Size of punch area
     PRTSIZ    DCW  @132@              * Size of print area
     EOS       DCW  @'@                * End Of String char
     EOL       DCW  @;@                * End Of Line char

               ORG  87
     X1        DSA  0                  * INDEX REGISTER 1
               ORG  92
     X2        DSA  0                  * INDEX REGISTER 2
               ORG  97
     X3        DSA  0                  * INDEX REGISTER 3
     
     * I need a single digit flag - should I replace this with a DA?
     RF        EQU  150
     
     ****************************************************************  

     * SET THE START POSITION OF CODE
               ORG  2200
     START     NOP  

     * SET THE STACK POINTER
               SBR  X2,400

               MCW  X2,X3
               LCA  @69105@,2005
               LCA  @201@,2025
               LCA  @200@,2028
               LCA  @081@,2033
               LCA  EOS,2022
               LCA  @F@,2021
               LCA  @E@,2020
               LCA  @D@,2019
               LCA  @C@,2018
               LCA  @B@,2017
               LCA  @A@,2016
               LCA  @9@,2015
               LCA  @8@,2014
               LCA  @7@,2013
               LCA  @6@,2012
               LCA  @5@,2011
               LCA  @4@,2010
               LCA  @3@,2009
               LCA  @2@,2008
               LCA  @1@,2007
               LCA  @0@,2006
               LCA  EOS,2040
               LCA  @C@,2039
               LCA  @%@,2038
               LCA  @D@,2037
               LCA  @%@,2036
               LCA  EOS,2077
               LCA  EOL,2076
               LCA  EOL,2075
               LCA  @S@,2074
               LCA  @N@,2073
               LCA  @O@,2072
               LCA  @I@,2071
               LCA  @T@,2070
               LCA  @A@,2069
               LCA  @R@,2068
               LCA  @E@,2067
               LCA  @T@,2066
               LCA  @I@,2065
               LCA  @ @,2064
               LCA  @D@,2063
               LCA  @%@,2062
               LCA  @ @,2061
               LCA  @H@,2060
               LCA  @T@,2059
               LCA  @I@,2058
               LCA  @W@,2057
               LCA  @ @,2056
               LCA  @E@,2055
               LCA  @L@,2054
               LCA  @G@,2053
               LCA  @N@,2052
               LCA  @A@,2051
               LCA  @I@,2050
               LCA  @R@,2049
               LCA  @T@,2048
               LCA  @ @,2047
               LCA  @L@,2046
               LCA  @A@,2045
               LCA  @C@,2044
               LCA  @S@,2043
               LCA  @A@,2042
               LCA  @P@,2041
               LCA  EOS,2085
               LCA  EOL,2084
               LCA  @.@,2083
               LCA  @E@,2082
               LCA  @N@,2081
               LCA  @O@,2080
               LCA  @D@,2079
               LCA  EOL,2078
               B    LBCAAA
               H    
     * FunctionDefinition((36))
     LKBAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3
     * BlockStatement(LLBAAA:null:7)
               MA   @007@,X2
     * Assignment(arg=((*char) (( &cformat_str ) + (15997))))
     * Addition(( &cformat_str )+(15997))
     * AddressOfExpression(cformat_str)
     * Push(@I9G@:3)
               MA   @003@,X2
               LCA  @I9G@,0+X2
               MA   X3,0+X2
     * ConstantExpression(15997)
     * Push(@I9G@:3)
               MA   @003@,X2
               LCA  @I9G@,0+X2
               MA   0+X2,15997+X2
     * Pop(3)
               MA   @I9G@,X2
     * Push(@006@:3)
               MA   @003@,X2
               LCA  @006@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:3)
               LCA  0+X2,0+X1
               MA   @I9G@,X2
     LHCAAA    NOP  
     * NotEqualExpression((c = ( *(cformat_str++) )):'\0')
     * Assignment(c=( *(cformat_str++) ))
     * DereferenceExpression((cformat_str++))
     * PostIncrement(cformat_str)
     * Push(@I9G@:3)
               MA   @003@,X2
               LCA  @I9G@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:3)
               MA   @003@,X2
               LCA  0+X1,0+X2
               MA   @001@,0+X1
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:1)
               MA   @001@,X2
               LCA  0+X1,0+X2
     * Push(@007@:3)
               MA   @003@,X2
               LCA  @007@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
               LCA  0+X2,0+X1
     * ConstantExpression(0)
     * Push(EOS:1)
               MA   @001@,X2
               LCA  EOS,0+X2
               C    0+X2,15999+X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               BE   LJCAAA
               B    LKCAAA
     LJCAAA    MCW  @00000@,0+X2
     LKCAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LICAAA,5+X2, 
     * BlockStatement(LMBAAA:LLBAAA:0)
     * if(retree.statement.ExpressionStatement@2b439bd9:retree.statement.BlockStatement@63acd9bf)
     * NotEqualExpression(c:'%')
     * VariableExpression(c:7:false)
     * Push(7+X3:1)
               MA   @001@,X2
               LCA  7+X3,0+X2
     * ConstantExpression(37)
     * Push(@%@:1)
               MA   @001@,X2
               LCA  @%@,0+X2
               C    0+X2,15999+X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               BE   LNCAAA
               B    LOCAAA
     LNCAAA    MCW  @00000@,0+X2
     LOCAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LLCAAA,5+X2, 
     * FunctionCallExpr((20))
     * Push(5)
               MA   @005@,X2
     * VariableExpression(c:7:false)
     * Push(7+X3:1)
               MA   @001@,X2
               LCA  7+X3,0+X2
     * Push(X3:3)
               MA   @003@,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LUAAAA
     * Pop(X3:3)
               LCA  0+X2,X3
               MA   @I9G@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(5)
               MA   @I9E@,X2
               B    LMCAAA
     LLCAAA    NOP  
     * BlockStatement(LNBAAA:LMBAAA:0)
     * Assignment(c=( *(cformat_str++) ))
     * DereferenceExpression((cformat_str++))
     * PostIncrement(cformat_str)
     * Push(@I9G@:3)
               MA   @003@,X2
               LCA  @I9G@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:3)
               MA   @003@,X2
               LCA  0+X1,0+X2
               MA   @001@,0+X1
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:1)
               MA   @001@,X2
               LCA  0+X1,0+X2
     * Push(@007@:3)
               MA   @003@,X2
               LCA  @007@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:1)
               LCA  0+X2,0+X1
               MA   @I9I@,X2
     * if(retree.statement.BlockStatement@690bbdb8:retree.statement.IfStatement@1d4b0e9)
     * EqualExpression(c:'%')
     * VariableExpression(c:7:false)
     * Push(7+X3:1)
               MA   @001@,X2
               LCA  7+X3,0+X2
     * ConstantExpression(37)
     * Push(@%@:1)
               MA   @001@,X2
               LCA  @%@,0+X2
               C    0+X2,15999+X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
               BE   LRCAAA
               B    LSCAAA
     LRCAAA    MCW  @00001@,0+X2
     LSCAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LPCAAA,5+X2, 
     * BlockStatement(LOBAAA:LNBAAA:0)
     * FunctionCallExpr((20))
     * Push(5)
               MA   @005@,X2
     * ConstantExpression(37)
     * Push(@%@:1)
               MA   @001@,X2
               LCA  @%@,0+X2
     * Push(X3:3)
               MA   @003@,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LUAAAA
     * Pop(X3:3)
               LCA  0+X2,X3
               MA   @I9G@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(5)
               MA   @I9E@,X2
     LOBAAA    NOP  
               BCE  LNBAAA,RF,R
               B    LQCAAA
     LPCAAA    NOP  
     * if(retree.statement.BlockStatement@32aa91ef:retree.statement.IfStatement@5c52fbe5)
     * EqualExpression(c:'C')
     * VariableExpression(c:7:false)
     * Push(7+X3:1)
               MA   @001@,X2
               LCA  7+X3,0+X2
     * ConstantExpression(67)
     * Push(@C@:1)
               MA   @001@,X2
               LCA  @C@,0+X2
               C    0+X2,15999+X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
               BE   LVCAAA
               B    LWCAAA
     LVCAAA    MCW  @00001@,0+X2
     LWCAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LTCAAA,5+X2, 
     * BlockStatement(LPBAAA:LNBAAA:0)
     * FunctionCallExpr((20))
     * Push(5)
               MA   @005@,X2
     * DereferenceExpression((arg--))
     * PostDecrement(arg)
     * Push(@006@:3)
               MA   @003@,X2
               LCA  @006@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:3)
               MA   @003@,X2
               LCA  0+X1,0+X2
               MA   @I9I@,0+X1
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:1)
               MA   @001@,X2
               LCA  0+X1,0+X2
     * Push(X3:3)
               MA   @003@,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LUAAAA
     * Pop(X3:3)
               LCA  0+X2,X3
               MA   @I9G@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(5)
               MA   @I9E@,X2
     LPBAAA    NOP  
               BCE  LNBAAA,RF,R
               B    LUCAAA
     LTCAAA    NOP  
     * if(retree.statement.BlockStatement@4c17a6bd:retree.statement.IfStatement@24c3e952)
     * EqualExpression(c:'S')
     * VariableExpression(c:7:false)
     * Push(7+X3:1)
               MA   @001@,X2
               LCA  7+X3,0+X2
     * ConstantExpression(83)
     * Push(@S@:1)
               MA   @001@,X2
               LCA  @S@,0+X2
               C    0+X2,15999+X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
               BE   LZCAAA
               B    LADAAA
     LZCAAA    MCW  @00001@,0+X2
     LADAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LXCAAA,5+X2, 
     * BlockStatement(LQBAAA:LNBAAA:0)
     * FunctionCallExpr((26))
     * Push(5)
               MA   @005@,X2
     * DereferenceExpression(((**char) arg))
     * VariableExpression(arg:6:false)
     * Push(6+X3:3)
               MA   @003@,X2
               LCA  6+X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:3)
               MA   @003@,X2
               LCA  0+X1,0+X2
     * Push(X3:3)
               MA   @003@,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LABAAA
     * Pop(X3:3)
               LCA  0+X2,X3
               MA   @I9G@,X2
     * Pop(3)
               MA   @I9G@,X2
     * Pop(5)
               MA   @I9E@,X2
     * Assignment(arg=(arg + (15997)))
     * Addition(arg+(15997))
     * VariableExpression(arg:6:false)
     * Push(6+X3:3)
               MA   @003@,X2
               LCA  6+X3,0+X2
     * ConstantExpression(15997)
     * Push(@I9G@:3)
               MA   @003@,X2
               LCA  @I9G@,0+X2
               MA   0+X2,15997+X2
     * Pop(3)
               MA   @I9G@,X2
     * Push(@006@:3)
               MA   @003@,X2
               LCA  @006@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:3)
               LCA  0+X2,0+X1
               MA   @I9G@,X2
     LQBAAA    NOP  
               BCE  LNBAAA,RF,R
               B    LYCAAA
     LXCAAA    NOP  
     * if(retree.statement.BlockStatement@3a0b1959:retree.statement.ReturnStatement@2ead3fd4)
     * EqualExpression(c:'D')
     * VariableExpression(c:7:false)
     * Push(7+X3:1)
               MA   @001@,X2
               LCA  7+X3,0+X2
     * ConstantExpression(68)
     * Push(@D@:1)
               MA   @001@,X2
               LCA  @D@,0+X2
               C    0+X2,15999+X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
               BE   LDDAAA
               B    LEDAAA
     LDDAAA    MCW  @00001@,0+X2
     LEDAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LBDAAA,5+X2, 
     * BlockStatement(LRBAAA:LNBAAA:7)
               MA   @007@,X2
     * FunctionCallExpr((15))
     * Push(3)
               MA   @003@,X2
     * ConstantExpression(10)
     * Push(@00010@:5)
               MA   @005@,X2
               LCA  @00010@,0+X2
     * ArrayNameExpresssion(a:char [7])
     * Push(@008@:3)
               MA   @003@,X2
               LCA  @008@,0+X2
               MA   X3,0+X2
     * DereferenceExpression(((*int) arg))
     * VariableExpression(arg:6:false)
     * Push(6+X3:3)
               MA   @003@,X2
               LCA  6+X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:5)
               MA   @005@,X2
               LCA  0+X1,0+X2
     * Push(X3:3)
               MA   @003@,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LPAAAA
     * Pop(X3:3)
               LCA  0+X2,X3
               MA   @I9G@,X2
     * Pop(5)
               MA   @I9E@,X2
     * Pop(3)
               MA   @I9G@,X2
     * Pop(5)
               MA   @I9E@,X2
     * Pop(3)
               MA   @I9G@,X2
     * FunctionCallExpr((26))
     * Push(5)
               MA   @005@,X2
     * ArrayNameExpresssion(a:char [7])
     * Push(@008@:3)
               MA   @003@,X2
               LCA  @008@,0+X2
               MA   X3,0+X2
     * Push(X3:3)
               MA   @003@,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LABAAA
     * Pop(X3:3)
               LCA  0+X2,X3
               MA   @I9G@,X2
     * Pop(3)
               MA   @I9G@,X2
     * Pop(5)
               MA   @I9E@,X2
     * Assignment(arg=(arg + (15995)))
     * Addition(arg+(15995))
     * VariableExpression(arg:6:false)
     * Push(6+X3:3)
               MA   @003@,X2
               LCA  6+X3,0+X2
     * ConstantExpression(15995)
     * Push(@I9E@:3)
               MA   @003@,X2
               LCA  @I9E@,0+X2
               MA   0+X2,15997+X2
     * Pop(3)
               MA   @I9G@,X2
     * Push(@006@:3)
               MA   @003@,X2
               LCA  @006@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:3)
               LCA  0+X2,0+X1
               MA   @I9G@,X2
     LRBAAA    NOP  
               MA   @I9C@,X2
               BCE  LNBAAA,RF,R
               B    LCDAAA
     LBDAAA    NOP  
     * set the return flag, so we know do deallocate our stack
               MCW  @R@,RF
     * and branch
               B    LNBAAA
     LCDAAA    NOP  
     LYCAAA    NOP  
     LUCAAA    NOP  
     LQCAAA    NOP  
     LNBAAA    NOP  
               BCE  LMBAAA,RF,R
     LMCAAA    NOP  
     LMBAAA    NOP  
               BCE  LLBAAA,RF,R
               B    LHCAAA
     LICAAA    NOP  
     LLBAAA    NOP  
               MA   @I9C@,X2
               MCW  @ @,RF
               LCA  3+X3,X1
               B    0+X1
     * FunctionDefinition((47))
     LVBAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3
     * BlockStatement(LWBAAA:null:14)
               MA   @014@,X2
     * ForStatement((i = 1),(i < d)'(i++):retree.statement.BlockStatement@3b8e754c:LYBAAA:LZBAAA:LACAAA)
     * Assignment(i=1)
     * ConstantExpression(1)
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
     * Push(@008@:3)
               MA   @003@,X2
               LCA  @008@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:5)
               LCA  0+X2,0+X1
               MA   @I9E@,X2
     LYBAAA    NOP  
     * LessThanExpression(i:d)
     * VariableExpression(i:8:false)
     * Push(8+X3:5)
               MA   @005@,X2
               LCA  8+X3,0+X2
               B    LFDAAA
     * VariableExpression(d:-9:false)
     * Push(15991+X3:5)
               MA   @005@,X2
               LCA  15991+X3,0+X2
               B    LFDAAA
               C    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
               MCW  @00000@,0+X2
               BL   LHDAAA
               B    LIDAAA
     LHDAAA    MCW  @00001@,0+X2
     LIDAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LZBAAA,5+X2, 
     * BlockStatement(LXBAAA:LWBAAA:0)
     * FunctionCallExpr((36))
     * Push(5)
               MA   @005@,X2
     * TernaryExpression((i < (d - 1)):' ':'\n')
     * LessThanExpression(i:(d - 1))
     * VariableExpression(i:8:false)
     * Push(8+X3:5)
               MA   @005@,X2
               LCA  8+X3,0+X2
               B    LFDAAA
     * Subtraction(d-1)
     * VariableExpression(d:-9:false)
     * Push(15991+X3:5)
               MA   @005@,X2
               LCA  15991+X3,0+X2
     * ConstantExpression(1)
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               S    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
               B    LFDAAA
               C    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
               MCW  @00000@,0+X2
               BL   LLDAAA
               B    LMDAAA
     LLDAAA    MCW  @00001@,0+X2
     LMDAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LJDAAA,5+X2, 
     * ConstantExpression(32)
     * Push(@ @:1)
               MA   @001@,X2
               LCA  @ @,0+X2
               B    LKDAAA
     LJDAAA    NOP  
     * ConstantExpression(10)
     * Push(EOL:1)
               MA   @001@,X2
               LCA  EOL,0+X2
     LKDAAA    NOP  
     * VariableExpression(v:13:false)
     * Push(13+X3:5)
               MA   @005@,X2
               LCA  13+X3,0+X2
     * ArrayNameExpresssion("%d%c":char [5])
     * Push(@!36@:3)
               MA   @003@,X2
               LCA  @!36@,0+X2
     * Push(X3:3)
               MA   @003@,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LKBAAA
     * Pop(X3:3)
               LCA  0+X2,X3
               MA   @I9G@,X2
     * Pop(3)
               MA   @I9G@,X2
     * Pop(5)
               MA   @I9E@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(5)
               MA   @I9E@,X2
     LXBAAA    NOP  
               BCE  LWBAAA,RF,R
     LACAAA    NOP  
     * PostIncrement(i)
     * Push(@008@:3)
               MA   @003@,X2
               LCA  @008@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
               A    @00001@,0+X1
               B    LYBAAA
     LZBAAA    NOP  
     * TernaryExpression((10 >= d):(47( y x (d + 1))):0)
     * GreaterThanOrEqualExpression(10:d)
     * ConstantExpression(10)
     * Push(@00010@:5)
               MA   @005@,X2
               LCA  @00010@,0+X2
               B    LFDAAA
     * VariableExpression(d:-9:false)
     * Push(15991+X3:5)
               MA   @005@,X2
               LCA  15991+X3,0+X2
               B    LFDAAA
               C    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
               MCW  @00001@,0+X2
               BL   LPDAAA
               B    LQDAAA
     LPDAAA    MCW  @00000@,0+X2
     LQDAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LNDAAA,5+X2, 
     * FunctionCallExpr((47))
     * Push(5)
               MA   @005@,X2
     * Addition(d+1)
     * VariableExpression(d:-9:false)
     * Push(15991+X3:5)
               MA   @005@,X2
               LCA  15991+X3,0+X2
     * ConstantExpression(1)
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               A    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * VariableExpression(x:-3:false)
     * Push(15997+X3:3)
               MA   @003@,X2
               LCA  15997+X3,0+X2
     * VariableExpression(y:-6:false)
     * Push(15994+X3:3)
               MA   @003@,X2
               LCA  15994+X3,0+X2
     * Push(X3:3)
               MA   @003@,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LVBAAA
     * Pop(X3:3)
               LCA  0+X2,X3
               MA   @I9G@,X2
     * Pop(3)
               MA   @I9G@,X2
     * Pop(3)
               MA   @I9G@,X2
     * Pop(5)
               MA   @I9E@,X2
               B    LODAAA
     LNDAAA    NOP  
     * ConstantExpression(0)
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
     LODAAA    NOP  
     * Pop(15986+X3:5)
               LCA  0+X2,15986+X3
               MA   @I9E@,X2
     * set the return flag, so we know do deallocate our stack
               MCW  @R@,RF
     * and branch
               B    LWBAAA
     LWBAAA    NOP  
               MA   @I8F@,X2
               MCW  @ @,RF
               LCA  3+X3,X1
               B    0+X1
     * FunctionDefinition((15))
     LPAAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3
     * BlockStatement(LQAAAA:null:14)
               LCA  @!06@,9+X3
               LCA  @00001@,14+X3
               MA   @014@,X2
     * Assignment(start=str)
     * VariableExpression(str:-8:false)
     * Push(15992+X3:3)
               MA   @003@,X2
               LCA  15992+X3,0+X2
     * Push(@006@:3)
               MA   @003@,X2
               LCA  @006@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:3)
               LCA  0+X2,0+X1
               MA   @I9G@,X2
     * if(retree.statement.BlockStatement@2d0d20ce:retree.statement.IfStatement@38e4cb7d)
     * LessThanExpression(value:0)
     * VariableExpression(value:-3:false)
     * Push(15997+X3:5)
               MA   @005@,X2
               LCA  15997+X3,0+X2
               B    LFDAAA
     * ConstantExpression(0)
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
               B    LFDAAA
               C    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
               MCW  @00000@,0+X2
               BL   LTDAAA
               B    LUDAAA
     LTDAAA    MCW  @00001@,0+X2
     LUDAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LRDAAA,5+X2, 
     * BlockStatement(LRAAAA:LQAAAA:0)
     * Assignment(( *(str++) )='-')
     * ConstantExpression(45)
     * Push(@-@:1)
               MA   @001@,X2
               LCA  @-@,0+X2
     * PostIncrement(str)
     * Push(@I9B@:3)
               MA   @003@,X2
               LCA  @I9B@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:3)
               MA   @003@,X2
               LCA  0+X1,0+X2
               MA   @001@,0+X1
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:1)
               LCA  0+X2,0+X1
               MA   @I9I@,X2
     * Assignment(value=(-value))
     * NegExpression(value)
     * VariableExpression(value:-3:false)
     * Push(15997+X3:5)
               MA   @005@,X2
               LCA  15997+X3,0+X2
               ZS   0+X2
               B    LFDAAA
     * Push(@I9G@:3)
               MA   @003@,X2
               LCA  @I9G@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:5)
               LCA  0+X2,0+X1
               MA   @I9E@,X2
     LRAAAA    NOP  
               BCE  LQAAAA,RF,R
               B    LSDAAA
     LRDAAA    NOP  
     * if(retree.statement.BlockStatement@34eb98b9:null)
     * EqualExpression(value:0)
     * VariableExpression(value:-3:false)
     * Push(15997+X3:5)
               MA   @005@,X2
               LCA  15997+X3,0+X2
               B    LFDAAA
     * ConstantExpression(0)
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
               B    LFDAAA
               C    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * Pop(5)
               MA   @I9E@,X2
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
               BE   LWDAAA
               B    LXDAAA
     LWDAAA    MCW  @00001@,0+X2
     LXDAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LVDAAA,5+X2, 
     * BlockStatement(LSAAAA:LQAAAA:0)
     * Assignment((str[0])='0')
     * ConstantExpression(48)
     * Push(@0@:1)
               MA   @001@,X2
               LCA  @0@,0+X2
     * VariableExpression(str:-8:false)
     * Push(15992+X3:3)
               MA   @003@,X2
               LCA  15992+X3,0+X2
     * ConstantExpression(0)
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
     * raw index on the stack
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * STACK TOP IS NOW ARRAY INDEX
               B    LYDAAA
               MA   0+X2,15997+X2
     * Pop(3)
               MA   @I9G@,X2
     * STACK top is location in array now.
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:1)
               LCA  0+X2,0+X1
               MA   @I9I@,X2
     * Assignment((str[1])='\0')
     * ConstantExpression(0)
     * Push(EOS:1)
               MA   @001@,X2
               LCA  EOS,0+X2
     * VariableExpression(str:-8:false)
     * Push(15992+X3:3)
               MA   @003@,X2
               LCA  15992+X3,0+X2
     * ConstantExpression(1)
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
     * raw index on the stack
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * STACK TOP IS NOW ARRAY INDEX
               B    LYDAAA
               MA   0+X2,15997+X2
     * Pop(3)
               MA   @I9G@,X2
     * STACK top is location in array now.
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:1)
               LCA  0+X2,0+X1
               MA   @I9I@,X2
     * VariableExpression(start:6:false)
     * Push(6+X3:3)
               MA   @003@,X2
               LCA  6+X3,0+X2
     * Pop(15984+X3:3)
               LCA  0+X2,15984+X3
               MA   @I9G@,X2
     * set the return flag, so we know do deallocate our stack
               MCW  @R@,RF
     * and branch
               B    LSAAAA
     LSAAAA    NOP  
               BCE  LQAAAA,RF,R
     LVDAAA    NOP  
     LSDAAA    NOP  
     LFEAAA    NOP  
     * LessThanOrEqualExpression(exp:retree.expression.DivideExpression@7400b581)
     * VariableExpression(exp:14:false)
     * Push(14+X3:5)
               MA   @005@,X2
               LCA  14+X3,0+X2
               B    LFDAAA
     * Divide(value/base)
     * VariableExpression(base:-11:false)
     * Push(15989+X3:5)
               MA   @005@,X2
               LCA  15989+X3,0+X2
     * VariableExpression(value:-3:false)
     * Push(15997+X3:5)
               MA   @005@,X2
               LCA  15997+X3,0+X2
               B    LHEAAA
               MCW  0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
               B    LFDAAA
               C    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
               MCW  @00001@,0+X2
               BH   LNEAAA
               B    LOEAAA
     LNEAAA    MCW  @00000@,0+X2
     LOEAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LGEAAA,5+X2, 
     * Assignment(exp=(exp * base))
     * Multiplication(exp*base)
     * VariableExpression(exp:14:false)
     * Push(14+X3:5)
               MA   @005@,X2
               LCA  14+X3,0+X2
     * VariableExpression(base:-11:false)
     * Push(15989+X3:5)
               MA   @005@,X2
               LCA  15989+X3,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * Push(@014@:3)
               MA   @003@,X2
               LCA  @014@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:5)
               LCA  0+X2,0+X1
               MA   @I9E@,X2
               B    LFEAAA
     LGEAAA    NOP  
     LPEAAA    NOP  
     * VariableExpression(exp:14:false)
     * Push(14+X3:5)
               MA   @005@,X2
               LCA  14+X3,0+X2
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LQEAAA,5+X2, 
     * BlockStatement(LTAAAA:LQAAAA:0)
     * Assignment(( *(str++) )=(digits[retree.expression.DivideExpression@5a8c63a6]))
     * SubScriptEpression(digits:retree.expression.DivideExpression@5a8c63a6)
     * VariableExpression(digits:9:false)
     * Push(9+X3:3)
               MA   @003@,X2
               LCA  9+X3,0+X2
     * Divide(value/exp)
     * VariableExpression(exp:14:false)
     * Push(14+X3:5)
               MA   @005@,X2
               LCA  14+X3,0+X2
     * VariableExpression(value:-3:false)
     * Push(15997+X3:5)
               MA   @005@,X2
               LCA  15997+X3,0+X2
               B    LHEAAA
               MCW  0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * raw index on the stack
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * STACK TOP IS NOW ARRAY INDEX
               B    LYDAAA
               MA   0+X2,15997+X2
     * Pop(3)
               MA   @I9G@,X2
     * STACK top is location in array now.
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:1)
               MA   @001@,X2
               LCA  0+X1,0+X2
     * PostIncrement(str)
     * Push(@I9B@:3)
               MA   @003@,X2
               LCA  @I9B@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:3)
               MA   @003@,X2
               LCA  0+X1,0+X2
               MA   @001@,0+X1
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:1)
               LCA  0+X2,0+X1
               MA   @I9I@,X2
     * Assignment(value=retree.expression.ModuloExpression@36e255bb)
     * ModuloExpression(value:exp)
     * VariableExpression(exp:14:false)
     * Push(14+X3:5)
               MA   @005@,X2
               LCA  14+X3,0+X2
     * VariableExpression(value:-3:false)
     * Push(15997+X3:5)
               MA   @005@,X2
               LCA  15997+X3,0+X2
               B    LHEAAA
     * Pop(5)
               MA   @I9E@,X2
     * Push(@I9G@:3)
               MA   @003@,X2
               LCA  @I9G@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:5)
               LCA  0+X2,0+X1
               MA   @I9E@,X2
     * Assignment(exp=retree.expression.DivideExpression@456a8423)
     * Divide(exp/base)
     * VariableExpression(base:-11:false)
     * Push(15989+X3:5)
               MA   @005@,X2
               LCA  15989+X3,0+X2
     * VariableExpression(exp:14:false)
     * Push(14+X3:5)
               MA   @005@,X2
               LCA  14+X3,0+X2
               B    LHEAAA
               MCW  0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * Push(@014@:3)
               MA   @003@,X2
               LCA  @014@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:5)
               LCA  0+X2,0+X1
               MA   @I9E@,X2
     LTAAAA    NOP  
               BCE  LQAAAA,RF,R
               B    LPEAAA
     LQEAAA    NOP  
     * Assignment(( *str )='\0')
     * ConstantExpression(0)
     * Push(EOS:1)
               MA   @001@,X2
               LCA  EOS,0+X2
     * VariableExpression(str:-8:false)
     * Push(15992+X3:3)
               MA   @003@,X2
               LCA  15992+X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:1)
               LCA  0+X2,0+X1
               MA   @I9I@,X2
     * VariableExpression(start:6:false)
     * Push(6+X3:3)
               MA   @003@,X2
               LCA  6+X3,0+X2
     * Pop(15984+X3:3)
               LCA  0+X2,15984+X3
               MA   @I9G@,X2
     * set the return flag, so we know do deallocate our stack
               MCW  @R@,RF
     * and branch
               B    LQAAAA
     LQAAAA    NOP  
               MA   @I8F@,X2
               MCW  @ @,RF
               LCA  3+X3,X1
               B    0+X1
     * FunctionDefinition((53))
     LBCAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3
     * BlockStatement(LCCAAA:null:118)
               MA   @118@,X2
     * ForStatement((i = 0),(i <= 10)'(i++):retree.statement.BlockStatement@2999d183:LECAAA:LFCAAA:LGCAAA)
     * Assignment(i=0)
     * ConstantExpression(0)
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
     * Push(@118@:3)
               MA   @003@,X2
               LCA  @118@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:5)
               LCA  0+X2,0+X1
               MA   @I9E@,X2
     LECAAA    NOP  
     * LessThanOrEqualExpression(i:10)
     * VariableExpression(i:118:false)
     * Push(118+X3:5)
               MA   @005@,X2
               LCA  118+X3,0+X2
               B    LFDAAA
     * ConstantExpression(10)
     * Push(@00010@:5)
               MA   @005@,X2
               LCA  @00010@,0+X2
               B    LFDAAA
               C    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
               MCW  @00001@,0+X2
               BH   LREAAA
               B    LSEAAA
     LREAAA    MCW  @00000@,0+X2
     LSEAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LFCAAA,5+X2, 
     * BlockStatement(LDCAAA:LCCAAA:0)
     * Assignment((x[i])=retree.expression.TernaryExpression@318a04cb)
     * TernaryExpression((i == 1):1:0)
     * EqualExpression(i:1)
     * VariableExpression(i:118:false)
     * Push(118+X3:5)
               MA   @005@,X2
               LCA  118+X3,0+X2
               B    LFDAAA
     * ConstantExpression(1)
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               B    LFDAAA
               C    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * Pop(5)
               MA   @I9E@,X2
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
               BE   LVEAAA
               B    LWEAAA
     LVEAAA    MCW  @00001@,0+X2
     LWEAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LTEAAA,5+X2, 
     * ConstantExpression(1)
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               B    LUEAAA
     LTEAAA    NOP  
     * ConstantExpression(0)
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
     LUEAAA    NOP  
     * ArrayNameExpresssion(x:int [11])
     * Push(@008@:3)
               MA   @003@,X2
               LCA  @008@,0+X2
               MA   X3,0+X2
     * VariableExpression(i:118:false)
     * Push(118+X3:5)
               MA   @005@,X2
               LCA  118+X3,0+X2
     * raw index on the stack
     * Push(@00005@:5)
               MA   @005@,X2
               LCA  @00005@,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * STACK TOP IS NOW ARRAY INDEX
               B    LYDAAA
               MA   0+X2,15997+X2
     * Pop(3)
               MA   @I9G@,X2
     * STACK top is location in array now.
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:5)
               LCA  0+X2,0+X1
               MA   @I9E@,X2
     * Assignment((y[i])=0)
     * ConstantExpression(0)
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
     * ArrayNameExpresssion(y:int [11])
     * Push(@063@:3)
               MA   @003@,X2
               LCA  @063@,0+X2
               MA   X3,0+X2
     * VariableExpression(i:118:false)
     * Push(118+X3:5)
               MA   @005@,X2
               LCA  118+X3,0+X2
     * raw index on the stack
     * Push(@00005@:5)
               MA   @005@,X2
               LCA  @00005@,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * STACK TOP IS NOW ARRAY INDEX
               B    LYDAAA
               MA   0+X2,15997+X2
     * Pop(3)
               MA   @I9G@,X2
     * STACK top is location in array now.
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:5)
               LCA  0+X2,0+X1
               MA   @I9E@,X2
     LDCAAA    NOP  
               BCE  LCCAAA,RF,R
     LGCAAA    NOP  
     * PostIncrement(i)
     * Push(@118@:3)
               MA   @003@,X2
               LCA  @118@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
               A    @00001@,0+X1
               B    LECAAA
     LFCAAA    NOP  
     * FunctionCallExpr((36))
     * Push(5)
               MA   @005@,X2
     * ConstantExpression(10)
     * Push(@00010@:5)
               MA   @005@,X2
               LCA  @00010@,0+X2
     * ArrayNameExpresssion("Pascal Triangle with %d iterations\n\n":char [37])
     * Push(@!41@:3)
               MA   @003@,X2
               LCA  @!41@,0+X2
     * Push(X3:3)
               MA   @003@,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LKBAAA
     * Pop(X3:3)
               LCA  0+X2,X3
               MA   @I9G@,X2
     * Pop(3)
               MA   @I9G@,X2
     * Pop(5)
               MA   @I9E@,X2
     * Pop(5)
               MA   @I9E@,X2
     * FunctionCallExpr((47))
     * Push(5)
               MA   @005@,X2
     * ConstantExpression(0)
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
     * ArrayNameExpresssion(y:int [11])
     * Push(@063@:3)
               MA   @003@,X2
               LCA  @063@,0+X2
               MA   X3,0+X2
     * ArrayNameExpresssion(x:int [11])
     * Push(@008@:3)
               MA   @003@,X2
               LCA  @008@,0+X2
               MA   X3,0+X2
     * Push(X3:3)
               MA   @003@,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LVBAAA
     * Pop(X3:3)
               LCA  0+X2,X3
               MA   @I9G@,X2
     * Pop(3)
               MA   @I9G@,X2
     * Pop(3)
               MA   @I9G@,X2
     * Pop(5)
               MA   @I9E@,X2
     * Pop(5)
               MA   @I9E@,X2
     * FunctionCallExpr((36))
     * Push(5)
               MA   @005@,X2
     * ArrayNameExpresssion("\nDone.\n":char [8])
     * Push(@!78@:3)
               MA   @003@,X2
               LCA  @!78@,0+X2
     * Push(X3:3)
               MA   @003@,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LKBAAA
     * Pop(X3:3)
               LCA  0+X2,X3
               MA   @I9G@,X2
     * Pop(3)
               MA   @I9G@,X2
     * Pop(5)
               MA   @I9E@,X2
     LCCAAA    NOP  
               MA   @H8B@,X2
               MCW  @ @,RF
               LCA  3+X3,X1
               B    0+X1
     * FunctionDefinition((5))
     LFAAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3
     * BlockStatement(LGAAAA:null:8)
               LCA  @0000J@,8+X3
               MA   @008@,X2
     LXEAAA    NOP  
     * NotEqualExpression((str[(++len)]):'\0')
     * SubScriptEpression(str:(++len))
     * VariableExpression(str:-3:false)
     * Push(15997+X3:3)
               MA   @003@,X2
               LCA  15997+X3,0+X2
     * PreIncrement(len)
     * Push(@008@:3)
               MA   @003@,X2
               LCA  @008@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
               A    @00001@,0+X1
     * Push(0+X1:5)
               MA   @005@,X2
               LCA  0+X1,0+X2
     * raw index on the stack
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * STACK TOP IS NOW ARRAY INDEX
               B    LYDAAA
               MA   0+X2,15997+X2
     * Pop(3)
               MA   @I9G@,X2
     * STACK top is location in array now.
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:1)
               MA   @001@,X2
               LCA  0+X1,0+X2
     * ConstantExpression(0)
     * Push(EOS:1)
               MA   @001@,X2
               LCA  EOS,0+X2
               C    0+X2,15999+X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               BE   LZEAAA
               B    LAFAAA
     LZEAAA    MCW  @00000@,0+X2
     LAFAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LYEAAA,5+X2, 
               B    LXEAAA
     LYEAAA    NOP  
     * VariableExpression(len:8:false)
     * Push(8+X3:5)
               MA   @005@,X2
               LCA  8+X3,0+X2
     * Pop(15994+X3:5)
               LCA  0+X2,15994+X3
               MA   @I9E@,X2
     * set the return flag, so we know do deallocate our stack
               MCW  @R@,RF
     * and branch
               B    LGAAAA
     LGAAAA    NOP  
               MA   @I9B@,X2
               MCW  @ @,RF
               LCA  3+X3,X1
               B    0+X1
     * FunctionDefinition((1))
     LBAAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3
     * BlockStatement(LCAAAA:null:3)
               MA   @003@,X2
     * Assignment(seed=retree.expression.ModuloExpression@6bc20de3)
     * ModuloExpression(((42 * seed) + 19):100000)
     * ConstantExpression(100000)
     * Push(@100000@:5)
               MA   @005@,X2
               LCA  @100000@,0+X2
     * Addition((42 * seed)+19)
     * Multiplication(42*seed)
     * ConstantExpression(42)
     * Push(@00042@:5)
               MA   @005@,X2
               LCA  @00042@,0+X2
     * VariableExpression(seed:2005:true)
     * Push(2005:5)
               MA   @005@,X2
               LCA  2005,0+X2
               M    15995+X2,6+X2
               SW   2+X2
               LCA  6+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
     * ConstantExpression(19)
     * Push(@00019@:5)
               MA   @005@,X2
               LCA  @00019@,0+X2
               A    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
               B    LHEAAA
     * Pop(5)
               MA   @I9E@,X2
     * Push(@!05@:3)
               MA   @003@,X2
               LCA  @!05@,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:5)
               LCA  0+X2,0+X1
               MA   @I9E@,X2
     * VariableExpression(seed:2005:true)
     * Push(2005:5)
               MA   @005@,X2
               LCA  2005,0+X2
     * Pop(15997+X3:5)
               LCA  0+X2,15997+X3
               MA   @I9E@,X2
     * set the return flag, so we know do deallocate our stack
               MCW  @R@,RF
     * and branch
               B    LCAAAA
     LCAAAA    NOP  
               MA   @I9G@,X2
               MCW  @ @,RF
               LCA  3+X3,X1
               B    0+X1
     * FunctionDefinition((20))
     LUAAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3
     * BlockStatement(LVAAAA:null:3)
               MA   @003@,X2
     * if(retree.statement.BlockStatement@111de95a:retree.statement.BlockStatement@42c31c7d)
     * NotEqualExpression(c:'\n')
     * VariableExpression(c:-3:false)
     * Push(15997+X3:1)
               MA   @001@,X2
               LCA  15997+X3,0+X2
     * ConstantExpression(10)
     * Push(EOL:1)
               MA   @001@,X2
               LCA  EOL,0+X2
               C    0+X2,15999+X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               BE   LDFAAA
               B    LEFAAA
     LDFAAA    MCW  @00000@,0+X2
     LEFAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LBFAAA,5+X2, 
     * BlockStatement(LWAAAA:LVAAAA:0)
     * Assignment(( *(__putchar_pos++) )=c)
     * VariableExpression(c:-3:false)
     * Push(15997+X3:1)
               MA   @001@,X2
               LCA  15997+X3,0+X2
     * PostIncrement(__putchar_pos)
     * Push(@!25@:3)
               MA   @003@,X2
               LCA  @!25@,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:3)
               MA   @003@,X2
               LCA  0+X1,0+X2
               MA   @001@,0+X1
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:1)
               LCA  0+X2,0+X1
               MA   @I9I@,X2
     LWAAAA    NOP  
               BCE  LVAAAA,RF,R
               B    LCFAAA
     LBFAAA    NOP  
     * BlockStatement(LXAAAA:LVAAAA:0)
     LFFAAA    NOP  
     * GreaterThanOrEqualExpression(((int) __putchar_last):((int) __putchar_pos))
     * VariableExpression(__putchar_last:2028:true)
     * Push(2028:3)
               MA   @003@,X2
               LCA  2028,0+X2
               B    LHFAAA
               B    LFDAAA
     * VariableExpression(__putchar_pos:2025:true)
     * Push(2025:3)
               MA   @003@,X2
               LCA  2025,0+X2
               B    LHFAAA
               B    LFDAAA
               C    0+X2,15995+X2
     * Pop(5)
               MA   @I9E@,X2
               MCW  @00001@,0+X2
               BL   LQFAAA
               B    LRFAAA
     LQFAAA    MCW  @00000@,0+X2
     LRFAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LGFAAA,5+X2, 
     * BlockStatement(LYAAAA:LXAAAA:0)
     * Assignment(( *(__putchar_last--) )=' ')
     * ConstantExpression(32)
     * Push(@ @:1)
               MA   @001@,X2
               LCA  @ @,0+X2
     * PostDecrement(__putchar_last)
     * Push(@!28@:3)
               MA   @003@,X2
               LCA  @!28@,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:3)
               MA   @003@,X2
               LCA  0+X1,0+X2
               MA   @I9I@,0+X1
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:1)
               LCA  0+X2,0+X1
               MA   @I9I@,X2
     LYAAAA    NOP  
               BCE  LXAAAA,RF,R
               B    LFFAAA
     LGFAAA    NOP  
     * Assignment(__putchar_last=__putchar_pos)
     * VariableExpression(__putchar_pos:2025:true)
     * Push(2025:3)
               MA   @003@,X2
               LCA  2025,0+X2
     * Push(@!28@:3)
               MA   @003@,X2
               LCA  @!28@,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:3)
               LCA  0+X2,0+X1
               MA   @I9G@,X2
     * Assignment(__putchar_pos=(201))
     * ConstantExpression(201)
     * Push(@201@:3)
               MA   @003@,X2
               LCA  @201@,0+X2
     * Push(@!25@:3)
               MA   @003@,X2
               LCA  @!25@,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:3)
               LCA  0+X2,0+X1
               MA   @I9G@,X2
     * Start asm block
               W    
     * End asm block
     LXAAAA    NOP  
               BCE  LVAAAA,RF,R
     LCFAAA    NOP  
     * if(retree.statement.BlockStatement@3768442e:null)
     * EqualExpression(__putchar_pos:(333))
     * VariableExpression(__putchar_pos:2025:true)
     * Push(2025:3)
               MA   @003@,X2
               LCA  2025,0+X2
     * ConstantExpression(333)
     * Push(@333@:3)
               MA   @003@,X2
               LCA  @333@,0+X2
               C    0+X2,15997+X2
     * Pop(3)
               MA   @I9G@,X2
     * Pop(3)
               MA   @I9G@,X2
     * Push(@00000@:5)
               MA   @005@,X2
               LCA  @00000@,0+X2
               BE   LTFAAA
               B    LUFAAA
     LTFAAA    MCW  @00001@,0+X2
     LUFAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LSFAAA,5+X2, 
     * BlockStatement(LZAAAA:LVAAAA:0)
     * Assignment(__putchar_last=__putchar_pos)
     * VariableExpression(__putchar_pos:2025:true)
     * Push(2025:3)
               MA   @003@,X2
               LCA  2025,0+X2
     * Push(@!28@:3)
               MA   @003@,X2
               LCA  @!28@,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:3)
               LCA  0+X2,0+X1
               MA   @I9G@,X2
     * Assignment(__putchar_pos=(201))
     * ConstantExpression(201)
     * Push(@201@:3)
               MA   @003@,X2
               LCA  @201@,0+X2
     * Push(@!25@:3)
               MA   @003@,X2
               LCA  @!25@,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Pop(0+X1:3)
               LCA  0+X2,0+X1
               MA   @I9G@,X2
     * Start asm block
               W    
     * End asm block
     LZAAAA    NOP  
               BCE  LVAAAA,RF,R
     LSFAAA    NOP  
     LVAAAA    NOP  
               MA   @I9G@,X2
               MCW  @ @,RF
               LCA  3+X3,X1
               B    0+X1
     * FunctionDefinition((7))
     LHAAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3
     * BlockStatement(LIAAAA:null:3)
               MA   @003@,X2
     LVFAAA    NOP  
     * NotEqualExpression((( *(dest++) ) = ( *(src++) )):'\0')
     * Assignment(( *(dest++) )=( *(src++) ))
     * DereferenceExpression((src++))
     * PostIncrement(src)
     * Push(@I9D@:3)
               MA   @003@,X2
               LCA  @I9D@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:3)
               MA   @003@,X2
               LCA  0+X1,0+X2
               MA   @001@,0+X1
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:1)
               MA   @001@,X2
               LCA  0+X1,0+X2
     * PostIncrement(dest)
     * Push(@I9G@:3)
               MA   @003@,X2
               LCA  @I9G@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:3)
               MA   @003@,X2
               LCA  0+X1,0+X2
               MA   @001@,0+X1
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
               LCA  0+X2,0+X1
     * ConstantExpression(0)
     * Push(EOS:1)
               MA   @001@,X2
               LCA  EOS,0+X2
               C    0+X2,15999+X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               BE   LXFAAA
               B    LYFAAA
     LXFAAA    MCW  @00000@,0+X2
     LYFAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LWFAAA,5+X2, 
               B    LVFAAA
     LWFAAA    NOP  
     LIAAAA    NOP  
               MA   @I9G@,X2
               MCW  @ @,RF
               LCA  3+X3,X1
               B    0+X1
     * FunctionDefinition((26))
     LABAAA    SBR  3+X3
               SW   1+X3
               CW   2+X3
               CW   3+X3
     * BlockStatement(LBBAAA:null:3)
               MA   @003@,X2
     LZFAAA    NOP  
     * NotEqualExpression(( *s ):'\0')
     * DereferenceExpression(s)
     * VariableExpression(s:-3:false)
     * Push(15997+X3:3)
               MA   @003@,X2
               LCA  15997+X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:1)
               MA   @001@,X2
               LCA  0+X1,0+X2
     * ConstantExpression(0)
     * Push(EOS:1)
               MA   @001@,X2
               LCA  EOS,0+X2
               C    0+X2,15999+X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Push(@00001@:5)
               MA   @005@,X2
               LCA  @00001@,0+X2
               BE   LBGAAA
               B    LCGAAA
     LBGAAA    MCW  @00000@,0+X2
     LCGAAA    NOP  
               MCS  0+X2,0+X2
     * Pop(5)
               MA   @I9E@,X2
               BCE  LAGAAA,5+X2, 
     * BlockStatement(LCBAAA:LBBAAA:0)
     * FunctionCallExpr((20))
     * Push(5)
               MA   @005@,X2
     * DereferenceExpression((s++))
     * PostIncrement(s)
     * Push(@I9G@:3)
               MA   @003@,X2
               LCA  @I9G@,0+X2
               MA   X3,0+X2
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:3)
               MA   @003@,X2
               LCA  0+X1,0+X2
               MA   @001@,0+X1
     * Pop(X1:3)
               LCA  0+X2,X1
               MA   @I9G@,X2
     * Push(0+X1:1)
               MA   @001@,X2
               LCA  0+X1,0+X2
     * Push(X3:3)
               MA   @003@,X2
               LCA  X3,0+X2
               MCW  X2,X3
               B    LUAAAA
     * Pop(X3:3)
               LCA  0+X2,X3
               MA   @I9G@,X2
     * Pop(1)
               MA   @I9I@,X2
     * Pop(5)
               MA   @I9E@,X2
     LCBAAA    NOP  
               BCE  LBBAAA,RF,R
               B    LZFAAA
     LAGAAA    NOP  
     LBBAAA    NOP  
               MA   @I9G@,X2
               MCW  @ @,RF
               LCA  3+X3,X1
               B    0+X1
     LFDAAA    SBR  X1
     * Normalizes the zone bits of a number, leaving either A=0B=0
     * for a positive or A=0B=1 for a negative
     * Do nothing on either no zone bits or only a b zone bit
               BWZ  LGDAAA,0+X2,2
               BWZ  LGDAAA,0+X2,K
     * else clear the zone bits, as it is positive
               MZ   @ @,0+X2
     LGDAAA    B    0+X1
    ****************************************************************  
    ** DIVISION SNIPPET                                           **
    ****************************************************************  
     
     LHEAAA    SBR  LIEAAA+3           * SETUP RETURN ADDRESS
     * POP DIVIDEND
               MCW  0+X2, LJEAAA
               SBR  X2, 15995+X2

     * POP DIVISOR
               MCW  0+X2, LKEAAA
               SBR  X2, 15995+X2


               B    *+17
               
               DCW  @00000@                
               DC   @00000000000@        

               ZA   LJEAAA, *-7         * PUT DIVIDEND INTO WORKING BL
               D    LKEAAA, *-19        * DIVIDE
               MZ   *-22, *-21          * KILL THE ZONE BIT
               MZ   *-29, *-34          * KILL THE ZONE BIT
               MCW  *-41, LLEAAA        * PICK UP ANSWER
               SW   *-44                * SO I CAN PICKUP REMAINDER
               MCW  *-46, LMEAAA        * GET REMAINDER
               CW   *-55                * CLEAR THE WM
               MZ   LLEAAA-1, LLEAAA    * CLEANUP QUOTIENT BITZONE
               MZ   LMEAAA-1, LMEAAA    * CLEANUP REMAINDER BITZONE
               
     * PUSH REMAINDER
               SBR  X2, 5+X2
               SW   15996+X2
               MCW  LMEAAA, 0+X2
               
     * PUSH QUOTIENT
               SBR  X2, 5+X2
               SW   15996+X2
               MCW  LLEAAA, 0+X2

     LIEAAA    B    000                 * JUMP BACK
               
     LKEAAA    DCW  00000               * DIVISOR
     LJEAAA    DCW  00000               * DIVIDEND
     LLEAAA    DCW  00000               * QUOTIENT
     LMEAAA    DCW  00000               * REMAINDER
     LYDAAA    SBR  X1
     * Casts a 5-digit number to a 3-digit address
     * make a copy of the top of the stack
               SW   15998+X2
               LCA  0+X2,3+X2
               CW   15998+X2
     * zero out the zone bits of our copy
               MZ   @0@,3+X2
               MZ   @0@,2+X2
               MZ   @0@,1+X2
     * set the low-order digit's zone bits
               C    @04000@,0+X2
               BL   LBEAAA
               C    @08000@,0+X2
               BL   LAEAAA
               C    @12000@,0+X2
               BL   LZDAAA
               S    @12000@,0+X2
               MZ   @A@,3+X2
               B    LBEAAA
     LZDAAA    S    @08000@,0+X2
               MZ   @I@,3+X2
               B    LBEAAA
     LAEAAA    S    @04000@,0+X2
               MZ   @S@,3+X2
     * For some reason the zone bits get set - it still works though.
     LBEAAA    C    @01000@,0+X2
               BL   LEEAAA
               C    @02000@,0+X2
               BL   LDEAAA
               C    @03000@,0+X2
               BL   LCEAAA
               MZ   @A@,1+X2
               B    LEEAAA
     LCEAAA    MZ   @I@,1+X2
               B    LEEAAA
     LDEAAA    MZ   @S@,1+X2
     LEEAAA    LCA  3+X2,15998+X2
               SBR  X2,15998+X2
               B    0+X1
     LHFAAA    SBR  X1
     * Casts a 3-digit address to a 5-digit number
     * Make room on the stack for an int
               MA   @002@,X2
     * make a copy of the top of the stack
               LCA  15998+X2,3+X2
     * Now zero out the top of the stack
               LCA  @00000@,0+X2
     * Now copy back, shifted over 2 digits
               LCA  3+X2,0+X2
     * Now zero out the zone bits on the stack
               MZ   @0@,0+X2
               MZ   @0@,15999+X2
               MZ   @0@,15998+X2
     * check the high-order digit's zone bits
               BWZ  LIFAAA,1+X2,S
               BWZ  LJFAAA,1+X2,K
               BWZ  LKFAAA,1+X2,B
               B    LLFAAA
     LIFAAA    A    @01000@,0+X2
               B    LLFAAA
     LJFAAA    A    @02000@,0+X2
               B    LLFAAA
     LKFAAA    A    @03000@,0+X2
     LLFAAA    BWZ  LMFAAA,3+X2,S
               BWZ  LNFAAA,3+X2,K
               BWZ  LOFAAA,3+X2,B
               B    LPFAAA
     LMFAAA    A    @04000@,0+X2
               B    LPFAAA
     LNFAAA    A    @08000@,0+X2
               B    LPFAAA
     LOFAAA    A    @12000@,0+X2
     LPFAAA    B    0+X1
               END  START
