     *>>>>>>>>>
     .READ     EQU  001
     .PUNCH    EQU  101
     .PRINT    EQU  201 
               ORG  87
     X1        DSA  0                * INDEX REGISTER 1
               ORG  92
     X2        DSA  0                * INDEX REGISTER 2
               ORG  97
     X3        DSA  0                * INDEX REGISTER 3
     *
               ORG  340              *ORG JUST AFTER PRINT BUFFER
     *<<<<<<<<<
